### ISSUE TITLE
Create Role Command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#1005]
`s!createrole [color hex] <name>`

**Comment by R4H33M** [comment]
Can I claim this one?

**Comment by pedrofracassi** [comment]
It's yours!

**Comment by R4H33M** [comment]
Hello! I think I am done :) How do I test it? Should I run my own instance and try it out on discord?

**Comment by pedrofracassi** [comment]
Yup! If you need help setting up a testing instance,  join our server and ask around!

**Comment by R4H33M** [comment]
Done - PR #1018!  There is a few code style "errors", but apart from them, what do you think?
