### ISSUE TITLE
Give Role Command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#1006]
`s!giverole <user> <role name>`

This command should check if the user has permission to give roles and is able to give that role to that user (role can't be above the user's highest role, except if they're admin. Target user can't be above the user either)

**Comment by estevam31** [comment]
can I work on this?

**Comment by metehus** [comment]
> can I work on this?

sure

**Comment by Doges** [comment]
Working on it.
