### ISSUE TITLE
League of Legends wrong category

### ISSUE THREAD

**Issue by davipatury** [SwitchbladeBot/switchblade#1013]
**Bug description**
League of Legends commands doesn't have proper category.

**How to reproduce**
1. Run s!help
2. ![image](https://user-images.githubusercontent.com/10660904/66716746-c449c100-eda7-11e9-9747-6b1aea3feb97.png)

**Expected behavior**
League of Legends commands should be in the `Games` category.

**Comment by WilliamJohnFrancis** [comment]
PR submitted for this by adding ---  category: 'games', --- to command file (https://github.com/SwitchbladeBot/switchblade/pull/1019)
