### ISSUE TITLE
"Did you mean?" option for command typos

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#1034]
Let's say someone types `s!showertoughts`. Currently, as it's not a valid command, the bot wouldn't do anything, and the user might get confused.

A good solution to that is allowing server owners to turn on a "did you mean" feature, that could use https://fusejs.io/ to find the closest match to what the user just typed and send a message like this on the channel:

> Did you mean `s!showerthoughts`?

**Comment by dpaiv0** [comment]
ps: this should be guild-configurable. iirc, Discord Bot List and some servers like those don't like that much when that happens

**Comment by pedrofracassi** [comment]
> A good solution to that is **allowing server owners to turn on** a "did you mean" feature

**Comment by dpaiv0** [comment]
```js
const Fuse = require('fuse.js')
const fuse = new Fuse(commandList, { shouldSort: true, threshold: 0.6, location: 0, distance: 100, maxPatternLength: 32, minMatchCharLength: 1 })
return fuse.search("queeu")
```

**Comment by pedrofracassi** [comment]
Yup, that looks good

**Comment by pedrofracassi** [comment]
I've used Fuse for the LoR commands btw, give them a look

**Comment by Doges** [comment]
Not possible due new discord bot system
