### ISSUE TITLE
s!createrole usage is wrong

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#1065]
![image](https://user-images.githubusercontent.com/25179120/67637633-2849aa80-f8bb-11e9-9591-8fa7ddf80119.png)
![image](https://user-images.githubusercontent.com/25179120/67637635-2b449b00-f8bb-11e9-8775-c32a237acbab.png)

Params are out of order. it should be `[color] <role name>`

**Comment by Doges** [comment]
Fixed on 2ad216f
