### ISSUE TITLE
Packagist Search Command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#1069]
`s!packagist <package name>`

https://packagist.org/apidoc

**Comment by Ninjavin** [comment]
@pedrofracassi Can you assign this issue to me?
Also, can you please elaborate this issue?

**Comment by pedrofracassi** [comment]
Sure thing! It's supposed to be a SearchCommand, which is a class we use for standardizing these types of interactions. We have [many commands using it](https://github.com/SwitchbladeBot/switchblade/search?q=extends+SearchCommand), if you want to take a look.
