### ISSUE TITLE
Pedro pls get out of bed

### ISSUE THREAD

**Issue by justandras** [SwitchbladeBot/switchblade#1077]
![image](https://user-images.githubusercontent.com/32372119/70322532-a12d1200-182a-11ea-89ff-80b19dd2ea1d.png)
@pedrofracassi

**Comment by justandras** [comment]
@pedrofracassi bump

**Comment by metehus** [comment]
it was my mistake but @pedrofracassi wake up

**Comment by pedrofracassi** [comment]
Then go fix it @metehus :hahaa:

**Comment by arthureleven** [comment]
Please approve this.
