### ISSUE TITLE
Why not use Chalk instead of ansi escapes?

### ISSUE THREAD

**Issue by fernando457829** [SwitchbladeBot/switchblade#1080]
The code would much better with chalk:
```js
client.log('[36mHello World') // without Chalk
client.log(chalk.cyan('Hello World') // with Chalk
```

And we could add options on `client.log`, for example:
```js
client.log('Hello World', { tags: ['Test'], color: 'cyan' })
```

**Comment by metehus** [comment]
yeah, dont know why used this ansi too

**Comment by pedrofracassi** [comment]
We'll switch to Winston at some point in the future after we start using docker

**Comment by fernando457829** [comment]
> We'll switch to Winston at some point in the future after we start using docker

But maybe for now? I can do this

**Comment by metehus** [comment]
> > We'll switch to Winston at some point in the future after we start using docker
> 
> But maybe for now? I can do this

let the kid do it huh

**Comment by fernando457829** [comment]
> let the kid do it huh
?

**Comment by davipatury** [comment]
> > let the kid do it huh
> 
> ?

deixa os garoto brincar
