### ISSUE TITLE
grammatical problem with pay command

### ISSUE THREAD

**Issue by Assfugil** [SwitchbladeBot/switchblade#1086]
**Bug description**
if you pay someone 1 switchcoin,it will say that you paid it 1 switchcoin**s** instead of 1 switchcoin

**How to reproduce**
1.Run `s!pay<user> 1`
2.The bot said `You sent 1 switchcoins to <user>`
**Expected behavior**
The bot should said `You sent 1 switchcoin to <user>`
**Screenshot**
![image](https://user-images.githubusercontent.com/42699250/71556224-90aa3900-2a70-11ea-8649-a303fce53de6.png)

**Comment by pedrofracassi** [comment]
Easy one! I'll fix it later.

**Comment by metehus** [comment]
SwitchbladePay™
