### ISSUE TITLE
Can we please be able to enable/disable NSFW

### ISSUE THREAD

**Issue by focus17** [SwitchbladeBot/switchblade#1087]
Please

. this is not needed everywhere nor when you don't want it on the server

**Comment by Doges** [comment]
but, it only works with nsfw channels

**Comment by focus17** [comment]
Good point

**Comment by pedrofracassi** [comment]
You can disable NSFW commands using command rules on the dashboard. They won't disappear from `s!help`, but they'll stop working. We do plan to make them vanish from `s!help` when not available tho.
