### ISSUE TITLE
Use axios instead node-fetch

### ISSUE THREAD

**Issue by fersilva16** [SwitchbladeBot/switchblade#1096]
Reasons:
- Axios performs automatic transformations of JSON data.
- Axios is more secure, featuring built in cross site forgery (XSRF) protection
- Axios has better error handling
- Axios has interceptors
- Axios has the ability to monitor POST request progress

Source: [this post on medium](https://medium.com/@jeffrey.allen.lewis/http-requests-compared-why-axios-is-better-than-node-fetch-more-secure-can-handle-errors-better-39fde869a4a6)

**Comment by pedrofracassi** [comment]
sure go ahead

**Comment by metehus** [comment]
doing that on [sb next](https://github.com/SwitchbladeBot/switchblade-next/blob/api-wrapper/src/apis/Deezer.js#L10-L13) btw

**Comment by pedrofracassi** [comment]
are we?

**Comment by pedrofracassi** [comment]
ok sure, axios looks cool

**Comment by fernando457829** [comment]
> doing that on [sb next](https://github.com/SwitchbladeBot/switchblade-next/blob/api-wrapper/src/apis/Deezer.js?rgh-link-date=2020-07-08T14%3A43%3A22Z#L10-L13) btw

Also, `responseType` is "json" by default.
