### ISSUE TITLE
What about add json linting for translations?

### ISSUE THREAD

**Issue by fersilva16** [SwitchbladeBot/switchblade#1099]
In some prs, I see json corrections, adding spaces between keys and values, and others fixes.

To fix this, maybe, we can add a json lint, I think we must add [eslint-plugin-json](https://www.npmjs.com/package/eslint-plugin-json), and maybe [Prettier](https://prettier.io) too, because it auto fix and beautify all code in general.

**Comment by dpaiv0** [comment]
we're talking only about the en-US folder in the repo, right?

**Comment by fernando457829** [comment]
Yeah

**Comment by fernando457829** [comment]
and about prs fixing this errors, [there a example](https://github.com/SwitchbladeBot/switchblade/pull/1007/files#diff-cef86ee6ed8baced84b31fa6d69578e1)
