### ISSUE TITLE
why is DiscordBotList required

### ISSUE THREAD

**Issue by AkgunFatih** [SwitchbladeBot/switchblade#1105]
i dont want it

**Comment by Doges** [comment]
please, read our license, that's the first thing that we recommend before selfhosting, we don't give support or liability for non official instances

thanks

**Comment by AkgunFatih** [comment]
i don't give a shit about your license

**Comment by davipatury** [comment]
And we don't give a shit about you. Stop bothering us.

**Comment by pedrofracassi** [comment]
> i don't give a shit about your license

boy I bet your lawyer does

**Comment by Doges** [comment]
rude
