### ISSUE TITLE
Command idea: httpdog

### ISSUE THREAD

**Issue by redbrain** [SwitchbladeBot/switchblade#1113]
I mean, you already have httpcat, which is implemented in almost exactly the same way. rather than http.cat/404 , it would be httpstatusdogs.com/img/404.jpg. I'll fork and PR once approved.

**Comment by pedrofracassi** [comment]
I've assigned it to you. Feel free to open a PR whenever you're ready!

**Comment by redbrain** [comment]
thanks!

**Comment by redbrain** [comment]
Closing because it has been merged with dev branch.
