### ISSUE TITLE
@Switchblade#7531 money returns Switchblade's balance

### ISSUE THREAD

**Issue by bolsomito** [SwitchbladeBot/switchblade#112]
**Bug description**
![](https://i.imgur.com/4NK29DN.png)

**How to reproduce**
![](https://i.imgur.com/4NK29DN.png)

**Expected behavior**
You have **x** Switchcoins in your account

**Screenshots**
![](https://i.imgur.com/4NK29DN.png)

**Additional context**
pls fix

**Comment by davipatury** [comment]
#95 fixes it
