### ISSUE TITLE
Garena Free Fire Weapons Command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#1157]
`s!freefire weapon [name]`

This endpoint returns the locales we scrape data in: https://ffstaticdata.switchblade.xyz/metadata.json

And this one returns weapon data: https://ffstaticdata.switchblade.xyz/LOCALE/weapons.json

**Comment by zMigueel** [comment]
The locale needs to be informed with the command, right?

**Comment by pedrofracassi** [comment]
No, you should use the locale passed in the command run context. I believe the variable name is `locale`.
