### ISSUE TITLE
Remove DiscordUtils since it no longer serves any purpose

### ISSUE THREAD

**Issue by almeidx** [SwitchbladeBot/switchblade#1172]
**Bug description**

The only purpose of https://github.com/SwitchbladeBot/switchblade/blob/dev/src/utils/DiscordUtils.js was to polyfill the cleanContent method from Discord.js version 12, however, we are now using Discord.js v12 so we can just use their function instead of DiscordUtils.

**Comment by moruzerinho6** [comment]
#1137 [Uses it](https://github.com/SwitchbladeBot/switchblade/blob/2598593cd77e09a1b63069ad34177b1880987271/src/utils/DiscordUtils.js) where would we move that function to?

**Comment by almeidx** [comment]
> #1137 [Uses it](https://github.com/SwitchbladeBot/switchblade/blob/2598593cd77e09a1b63069ad34177b1880987271/src/utils/DiscordUtils.js) where would we move that function to?

Your `ensurePermissions()` method can stay. What I meant with this issue is that we can just use `cleanContent` from [Discord.js' Util](https://discord.js.org/#/docs/main/12.2.0/class/Util?scrollTo=s-cleanContent)
