### ISSUE TITLE
Fetch users globally whenever an ID is provided

### ISSUE THREAD

**Issue by almeidx** [SwitchbladeBot/switchblade#1174]
**Is your feature request related to a problem? Please describe.**
The UserParameter does not fetch users globally

**Describe the solution you'd like**
It should fetch users globally whenever a Snowflake is provided

**Additional context**
This can be done using [UserManager#fetch](https://discord.js.org/#/docs/main/12.2.0/class/UserManager?scrollTo=fetch) from Discord.js

**Comment by Doges** [comment]
due to discord new dev system blah blah blah
