### ISSUE TITLE
LanguageLayer "whatlanguage" Command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#1179]
`s!whatlanguage <text>` - Tells you what language a piece of text is in

https://languagelayer.com/

**Comment by Doges** [comment]
I'm gonna try it

**Comment by Doges** [comment]
Prob the api is not working, gonna try it l8r

![](https://i.imgur.com/nG6q43Y.png)

**Comment by Vicente015** [comment]
Hey, can I work on this? 🤔

**Comment by Doges** [comment]
Sure!
