### ISSUE TITLE
Hey i tried out your bot and really loved it 💖. I was considering to self host the bot and try to customise it a bit. 

### ISSUE THREAD

**Issue by Rayne231** [SwitchbladeBot/switchblade#1186]
i wanted to ask you that when i am self hosting the bot what are the dependencies and are there any files i need to add, remove (which are not required while self hosting) or edit (i already know i need to complete the `.env`)? tysm

**Comment by Rayne231** [comment]
can u give me basic instructions for self hosting 
how to install dependencies and everything

**Comment by Doges** [comment]
Hi! Please consider looking our self-hosting section on [readme](https://github.com/SwitchbladeBot/switchblade#self-hosting) before trying to self-host. We don't provide any type of support, and we are glad that you liked the bot, sorry for the inconvenience. Have a great day!

- ^DG
