### ISSUE TITLE
PetPet command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#1197]
`s!petpet`

![8259f921-17ea-4a6a-8221-341685dabdf8](https://user-images.githubusercontent.com/25179120/94045310-ac473380-fda5-11ea-8391-47059c6d7d43.gif)

---

![image](https://user-images.githubusercontent.com/25179120/94045263-9df91780-fda5-11ea-8e81-e00dfe188f0c.png)

https://www.npmjs.com/package/gif-encoder

https://benisland.neocities.org/petpet/

**Comment by perronosaurio** [comment]
https://github.com/jnordberg/gif.js
