### ISSUE TITLE
Hacktoberfest 2021 - Contribute to Switchblade and win free stickers!

### ISSUE THREAD

**Issue by Doges** [SwitchbladeBot/switchblade#1203]
<div align="center">
<br>
<img height="100" src="https://user-images.githubusercontent.com/25179120/94884779-c12a6380-0444-11eb-88f0-1254a2d21b97.png">
<h1>Hacktoberfest 2021</h1>
</div>

**We're happy to announce that we're participating _again_ of Hacktoberfest this year!** If you open 3 or more **valid pull requests** to our repositories during October, we'll mail you three fancy Switchblade stickers and a letter as a thank you for contributing to open source :)

Once you have your three Pull Requests open, join [our community discord](https://community.switchblade.xyz/) and message a core developer about your stickers. They'll verify your contributions and take your shipment address.

<details>
<summary>Click this to see how the stickers look!</summary>
<img src="https://user-images.githubusercontent.com/25179120/94884272-65aba600-0443-11eb-8374-d2c570ef385d.png">
</details>

Happy hacking!

**Comment by metehus** [comment]
why this an issue

**Comment by Doges** [comment]
bruh, just check the dev lounge

**Comment by Doges** [comment]
![](https://i.imgur.com/12Vxepj.jpeg)

**Comment by Doges** [comment]
Yeah, we are doing it again.
