### ISSUE TITLE
RubyGems Command Not working

### ISSUE THREAD

**Issue by Ninjavin** [SwitchbladeBot/switchblade#1233]
**Bug description**

`s!rubygems <package-name>` command is not working. It sends Switchblade to `is typing` mode indefinitely and there is no output.

**How to reproduce**

1. Run `s!rubygems <package-name>`

**Expected behavior**

The command should return information about the searched RubyGems package-name.

**Screenshots**

![image](https://user-images.githubusercontent.com/49443829/95071763-cd097480-0727-11eb-8c98-a5fa95faf538.png)

**Additional context**

**Comment by jaxxibae** [comment]
Will debug this ASAP.

**Comment by Doges** [comment]
Not a Bug, dev ops fault

![](https://i.imgur.com/gjgwcnq.png)

**Comment by pedrofracassi** [comment]
Did we fix it?
