### ISSUE TITLE
issue!!!1!!!!! fix fast

### ISSUE THREAD

**Issue by Doges** [SwitchbladeBot/switchblade#1269]
check the video below

https://user-images.githubusercontent.com/31023616/102886559-15d1ef00-4434-11eb-8b38-15e2be1076dc.mp4

**Comment by sayand0122** [comment]
Was this some kind of joke?

**Comment by Doges** [comment]
> 
> 
> Was this some kind of joke?

Yes

**Comment by Sloth-Panda** [comment]
would love  to get this done 🤣🤣

**Comment by jaxxibae** [comment]
I like jokes, but please refrain from doing this.

**Comment by Doges** [comment]
vai se fude
