### ISSUE TITLE
Purge Command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#127]
`s!purge [amount] [@user]` - Deletes X messages (default: 50)

Requires `MANAGE_MESSAGES`.

**Comment by pedrofracassi** [comment]
Maybe we could get more detailed, like having a second argument for filtering.

**Comment by bolsomito** [comment]
s!purge [amount] [@user] probably?

+ if no amount, prune 50
+ if amount but no user, prune amount
+ if amount and user, prune x messages from user
+ if no amount and user, prune 50 messages from user

**Comment by pedrofracassi** [comment]
Yeah, that would be nice. But how are we going to do it with the new args system?

**Comment by bolsomito** [comment]
leave that to me my friend, i'm going to do the almost-whole moderation part of things

**Comment by bolsomito** [comment]
![](https://i.imgur.com/o7jextr.png)

**Comment by pedrofracassi** [comment]
Should we start a moderation-commands branch?

**Comment by bolsomito** [comment]
yes, why not?
i'm doing planning on pen n' paper first

**Comment by pedrofracassi** [comment]
I'll create the branch & PR while you're at it.

**Comment by bolsomito** [comment]
thank you my friendo

**Comment by pedrofracassi** [comment]
Here we go: #137
