### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by tharunc** [SwitchbladeBot/switchblade#1274]
Hello there,
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time as a part of **DWOC**. Please assign me this issue.
For reference, kindly check out: https://github.com/apps/welcome

THANK YOU

**Comment by Doges** [comment]
Hey! Thanks for opening an issue, but our team prefers to welcome people personally, because it gives the person a "better feeling", anyway, thanks again for opening an issue.
