### ISSUE TITLE
Automating bot website

### ISSUE THREAD

**Issue by himanshu007-creator** [SwitchbladeBot/switchblade#1275]
I would like to work on this issue.I will create a script that will enable opening website from CLI.
Please add DWOC label to it and assign me this issue.

**Comment by Doges** [comment]
Uhhhh, can you please explain it with more details?

**Comment by himanshu007-creator** [comment]
> Uhhhh, can you please explain it with more details?

Yeash sure!
Basically I identified a problem.For people using ubuntu and similar operating systems, where all tasks are done via CLI, opening a website is a time consuming task.
For my code will open the website  when it will run.

**Comment by Doges** [comment]
In that case, we use the [portainer](https://www.portainer.io/), that also allow us to manage the entire docker machine/swarms using an machine-hosted website, anyway, thanks for opening an issue, have an excellent day and stay safe!

**Comment by Doges** [comment]
PS: It looks pretty good the idea, keep going! Its awesome
