### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [SwitchbladeBot/switchblade#1276]
To make README.md file beautiful and give credit to contributors
Like this
![image](https://user-images.githubusercontent.com/68433936/104682324-68908500-571a-11eb-8cb3-7c42b1c5172e.png)

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by pedrofracassi** [comment]
We have way too many contributors and that table would clog up our README way too much. Thanks for the idea though.
