### ISSUE TITLE
LMGTFY command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#128]
`s!lmgtfy <query>` ==> `https://lmgtfy.com/?q=<query>`

> **lmgtfy = (abbreviation) let me google that for you**
>
>www.lmgtfy.com lets you google for someone else. So for example, instead of answering a question, you get to be a smartass and answer it through Google!

**Comment by LoganArnett** [comment]
I can pick this one up too if it is still available

**Comment by pedrofracassi** [comment]
Please!
