### ISSUE TITLE
Generating Random Lorem Text

### ISSUE THREAD

**Issue by AsianCat54x** [SwitchbladeBot/switchblade#1341]
**New Command Idea**

- Create a new command, say "s!lorem" which will generate a random lorem ipsum text.

Here is a module for generating lorem ipsum text - https://github.com/knicklabs/lorem-ipsum.js

**Comment by Doges** [comment]
Hi, that's actually a good command, but, I think it may need some more things, like <number of paragraphs> and I'm not sure but, I think there is a REST API for this, it should be better than installing another package.

Thanks

**Comment by AsianCat54x** [comment]
As I am already assigned to 3 issues, I would like others thise who are interested to work on this issue.

**Comment by jaxxibae** [comment]
> I don't like much the idea of depending on a external service, id rather use a local library
Or, one could make its own version of lorem-ipsum.js.

**Comment by hannesfant** [comment]
Is anyone working on this? If not, please assign it to me and I'll get it sorted :)
