### ISSUE TITLE
.env is not working

### ISSUE THREAD

**Issue by GameWax** [SwitchbladeBot/switchblade#1373]
**Bug description**
I filled in the values in the .env file, but when I execute the code the console tells me invalid token and everything, so I came to a conclusion that .env values are not being imported in any other files and whether you fill or don't fill the env file, the errors will be the same that no value has been placed.

**How to reproduce**
<!--Steps to reproduce the unusual behavior:
1. Execute the bot

**Expected behavior**
If we fill the .env values, just like any other code, the env values should be imported in all files in the source and the execution should be successful and the bot comes online.

**Comment by Doges** [comment]
Hi! Sorry but we can't provide support for self-hosting but as I tested yesterday, It managed to run my instance with all environment variables. We highly recommend to use our [main instance](https://invite.switchblade.xyz). Thanks!

TIP: Check our package.json

**Comment by Doges** [comment]
ignore what I said,  just run `npm run start-dev`, it should work fine
