### ISSUE TITLE
When i try to start the bot i get this 

### ISSUE THREAD

**Issue by hotsu0p** [SwitchbladeBot/switchblade#1411]
(im also banned from support server bc i got hacked and now i got my acc cleared)

Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.

Node version
18.18.0

discord.js version
latest

**Comment by jpsl00** [comment]
Hi @hotsu0p 

Please refer to the [self-hosting](https://github.com/SwitchbladeBot/switchblade?tab=readme-ov-file#self-hosting) part of the readme
