### ISSUE TITLE
question

### ISSUE THREAD

**Issue by hotsu0p** [SwitchbladeBot/switchblade#1415]
Hello how can  contribute to this project? like what is needed?

**Comment by edwin-shdw** [comment]
https://github.com/SwitchbladeBot/switchblade?tab=readme-ov-file#contributing

**Comment by Doges** [comment]
Hi!
Thanks for your interest in contributing to Switchblade!!! We really appreciate your enthusiasm but unfortunately, at this time, the project is not actively maintained and there's uncertainty about its future. The current status of the project is unclear, and there's no plans for immediate updates or contributions.

If you have any further questions or if there's anything else we can help you with, please feel free to join in our Discord server.
