### ISSUE TITLE
Coin Flip command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#143]
`s!coinflip` - Flips a coin
`s!betflip <bet> <heads|tails>` - Flips a coin and bets X switchcoins

**Comment by bolsomito** [comment]
we already have s!(coin)flip

**Comment by bolsomito** [comment]
but i'm doing it
fuck it

**Comment by bolsomito** [comment]
ok, we don't

**Comment by bolsomito** [comment]
![](https://raw.githubusercontent.com/bolsomito/koi/master/bin/assets/heads.png)
![](https://raw.githubusercontent.com/bolsomito/koi/master/bin/assets/tails.png)
