### ISSUE TITLE
s!isitup breaks if path is added to the URL

### ISSUE THREAD

**Issue by LogGame-HU-DEaN** [SwitchbladeBot/switchblade#146]
**Bug description**
Adding a path `e.g. github.com`**/SwitchbladeBot** or just a `/` after the top-level domain causes the bot to write indefinitely. The same happens if you add `http(s)://`, because Discord automatically adds the `/` after the TLD.

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run s!isitup google.com/

**Expected behavior**
The usual s!isitup answer should appear.

**Comment by bolsomito** [comment]
As far as I know, this is a problem w/ isitup.org's API. I don't know why Pedro used it, as we can use request / snekfetch for that. I'm going to fix this asap

**Comment by pedrofracassi** [comment]
I still think using the API is better, because they're specialized in it.

Idk, maybe if a website has a lot of redirects, we'll not be the ones dealing with it.

**Comment by pedrofracassi** [comment]
The API deals with `/` and `http://` without any problems.

**Comment by pedrofracassi** [comment]
Maybe we need to clean the string that Discord gives us?

**Comment by bolsomito** [comment]
we already do that
