### ISSUE TITLE
Create / Delete emoji commands

### ISSUE THREAD

**Issue by dpaiv0** [SwitchbladeBot/switchblade#164]
`s!createemoji <link> <name>`
`s!deleteemoji <:emoji: / name>`

**Comment by pedrofracassi** [comment]
Requires `MANAGE_EMOJI`

**Comment by bolsomito** [comment]
i know you dumbfuck

**Comment by dpaiv0** [comment]
will do too

**Comment by dpaiv0** [comment]
Closing as it has been done in #839
