### ISSUE TITLE
s!strawpoll format breaks when Discord formatting codes are used

### ISSUE THREAD

**Issue by LogGame-HU-DEaN** [SwitchbladeBot/switchblade#165]
**Bug description**
Using Discord formatting codes breaks the command format.

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run s!strawpoll including Discord formatting codes `**text**, ~~text~~`, and the like.

**Expected behavior**
The message should appear correctly.

**Screenshots**
![Broken beyond belief](https://user-images.githubusercontent.com/35978189/41917977-a3a17f36-795b-11e8-8109-2451830fc9fe.png)

**Comment by bolsomito** [comment]
ways to counter this:
+ use s!poll
+ remove formatting while processing the command
+ ???

**Comment by pedrofracassi** [comment]
Actually, `s!poll` would break too, @bolsomito

**Comment by pedrofracassi** [comment]
We can use REGEX to find the characters that are used in discord's formatting and add `\` before them.

**Comment by pedrofracassi** [comment]
Easy one, who wants to do it?

**Comment by Doges** [comment]
why not you

**Comment by pedrofracassi** [comment]
no u

**Comment by bolsomito** [comment]
yeah, `const Discord = require('discord.js'); Discord.Util.escapeMarkdown();` is a thing I just found

**Comment by pedrofracassi** [comment]
Ooooh, nice found! We can use that for sure
