### ISSUE TITLE
Brainfuck command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#170]
`s!brainfuck ++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.`
Runs brainfuck code

**Comment by upedd** [comment]
Could i do it?

**Comment by almeidx** [comment]
> Could i do it?

Yep.
