### ISSUE TITLE
s!deezer doesn't have its own strings

### ISSUE THREAD

**Issue by LogGame-HU-DEaN** [SwitchbladeBot/switchblade#173]
**Bug description**
Using s!deezer returns `deezer.commandUsage` and `No description provided`.

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run s!deezer

**Expected behavior**
The strings should appear.

**Screenshots**
![deezer.commandUsage](https://user-images.githubusercontent.com/35978189/41977997-193bdad2-7a21-11e8-8934-d540b590e6c7.png)
![No description provided](https://user-images.githubusercontent.com/35978189/41978014-234a8866-7a21-11e8-8c5d-382b2952577a.png)

**Comment by pedrofracassi** [comment]
@Doges your command, your problem 
![image](https://user-images.githubusercontent.com/25179120/41978453-4b72f068-79f8-11e8-97a8-7eb64fd9c923.png)
