### ISSUE TITLE
Some Soundcloud songs isn't working

### ISSUE THREAD

**Issue by Doges** [SwitchbladeBot/switchblade#176]
**Bug description**
When you try to play a soundcloud song, with some specific songs it retrives an error

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Play a soundcloud song which gives error

**Expected behavior**
No errors, and play music

**Screenshots**
![](https://idonthave.life/i/3t9g3.png)

**Comment by pedrofracassi** [comment]
"Play a soundcloud song which gives error" is very non-specific. Could you please link some songs that "gives error"?

**Comment by bolsomito** [comment]
https://soundcloud.com/hex-xx/skypierr-no-limit-2018

**Comment by bolsomito** [comment]
https://soundcloud.com/knadex/everyones-platinum-sequel-2014-edition
