### ISSUE TITLE
Bot responds wrongly when requesting to play private youtube video

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#181]
**Bug description**
Bot responds with "You need to be in a voice channel in order to do that." whenever someone tries to play a private YT video

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run c!play https://youtu.be/d4qAE39A1Dc (A private video)

**Expected behavior**
Respond with "Video is private or unavailable"

**Screenshots**
![error](https://puu.sh/AOHKq/a4f4978e2f.png)

**Additional context**
None

**Comment by davipatury** [comment]
https://github.com/SwitchbladeBot/switchblade/blob/master/src/commands/music/play.js#L27
