### ISSUE TITLE
Aliases for the s!setlanguage command

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#182]
Add aliases to the s!setlanguage command.
example:

Instead of just
s!setlanguage es-ES

You should also be able to write
s!setlanguage Spanish
s!setlanguage Español

**Comment by pedrofracassi** [comment]
@backend how are we going to do this?

**Comment by bolsomito** [comment]
this.aliases is a thi... oh

**Comment by pedrofracassi** [comment]
Oh

**Comment by davipatury** [comment]
Maybe we could use [cldr](https://www.npmjs.com/package/cldr).

**Comment by pedrofracassi** [comment]
Yeah, that looks good

**Comment by LogGame-HU-DEaN** [comment]
Isn't this done?

**Comment by pedrofracassi** [comment]
Yes it is
