### ISSUE TITLE
Language codes are case-sensitive in the s!setlanguage command

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#184]
**Bug description**
Language codes are case-sensitive in the s!setlanguage command. This means that for example s!setlanguage nb-no doesn't work while s!setlanguage nb-NO works

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run s!setlanguage nb-no
2. Now run s!setlanguage nb-NO

**Expected behavior**
It should change the language to the desired one, no matter you're using lower or uppercase

**Screenshots**
![case](https://media.discordapp.net/attachments/462655962507902986/462716783808479232/unknown.png?width=698&height=703)
**Additional context**
None

**Comment by bolsomito** [comment]
i do believe that this is intended, but #195 might "fix" that

**Comment by pedrofracassi** [comment]
It isn't intended, but I do think we should implement it.

**Comment by bolsomito** [comment]
uhum, but still, using `s!setlang Español` is better than `s!setlang es-ES`
