### ISSUE TITLE
s!fliptext command doesn't flip all characters, nor does it use the correct characters sometimes

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#188]
**Bug description**
s!fliptext command doesn't flip all characters, nor does it use the correct characters sometimes. Some examples are the characters "4" and ’

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run "s!fliptext" and enter numbers or characters like ’

**Expected behavior**
It should be able to flip the text correctly with the correct characters/flip all characters

**Screenshots**
https://puu.sh/AP3yg/2dc308ec8f.png

**Additional context**
https://puu.sh/AP3yA/cedd8b532e.png

**Comment by LogGame-HU-DEaN** [comment]
Afaik this happens because the UTF-8 charset does not have upside-down characters for those letters and numbers.
