### ISSUE TITLE
Problems with playing certain songs, "You need to be in a voice channel in order to do that."

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#189]
**Bug description**
Bot responds with "You need to be in a voice channel in order to do that." when trying to play some songs

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run s!play https://open.spotify.com/track/7wSJdVaQmJ1LlillSjMmWV?si=hAY12FPVSMaHog0EQbd-QQ

**Expected behavior**
Search for the song on youtube and play it

**Screenshots**
https://puu.sh/AP49G/57ae5969b9.png

**Additional context**
None

**Comment by davipatury** [comment]
Fixes by #183

**Comment by LBlend** [comment]
Whenever you call the command with a spotify link it looks it up on youtube, so it does work with spotify.
