### ISSUE TITLE
The bot replaces the Ñ with a P.

### ISSUE THREAD

**Issue by perronosaurio** [SwitchbladeBot/switchblade#191]
**Bug description**
The bot replaces the Ñ with a P in the SAMP command.

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run s!samp <ip>...

**Screenshots**
![image](https://user-images.githubusercontent.com/27968093/42135457-36be4b30-7d19-11e8-8a15-1cdc1c836dd3.png)

**Comment by pedrofracassi** [comment]
WTF lmao

**Comment by davipatury** [comment]
Probably an encode/decode problem.
