### ISSUE TITLE
s!dog displays a blank embed sometimes

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#2]
![image](https://user-images.githubusercontent.com/25179120/40029036-adfa4fc2-57b8-11e8-8ba4-6401f401aef3.png)

**How to reproduce:** Run `s!dog` really fast.

Probably related to ratelimiting.

**Comment by bolsomito** [comment]
As it seems, it is **not** related to ratelimiting. There are .mp4 files in the API, and as far as I know, RichEmbed "image" fields don't support any type of video.

**Comment by bolsomito** [comment]
What do you mean, do another request if the file type == .mp4 ?

**Comment by pedrofracassi** [comment]
Yeah. Not as shiny, but will work.

**Comment by xDoges** [comment]
Actually working on it.

**Comment by pedrofracassi** [comment]
Please only close issues after the PRs are merged.

**Comment by bolsomito** [comment]
Fixed in #8 and merged to `master`, closing ticket.
