### ISSUE TITLE
Amsterdam not listed on bot regions

### ISSUE THREAD

**Issue by Doges** [SwitchbladeBot/switchblade#219]
**Bug description**
Theres actually a amsterdam vip server on discord, and its not listed.

**Comment by bolsomito** [comment]
give me an example of a server that uses the Amsterdam region

**Comment by bolsomito** [comment]
i dare you

**Comment by bolsomito** [comment]
!11!11!111!!!

**Comment by Doges** [comment]
/r/amsterdam server

**Comment by bolsomito** [comment]
invite?

**Comment by Doges** [comment]
why i m gonna get the /r/amsterdam invite?

**Comment by bolsomito** [comment]
@Doges add "Frankfurt" and "London" to the list

**Comment by Doges** [comment]
closing beacuse its fixed
