### ISSUE TITLE
Netoland Command

### ISSUE THREAD

**Issue by Doges** [SwitchbladeBot/switchblade#230]
Show random photos from netoland

**Comment by Doges** [comment]
high priority

**Comment by Doges** [comment]
if you don't know what netoland is, ![](https://idonthave.life/i/296Eb.jpg)

**Comment by bolsomito** [comment]
fuck you doges

**Comment by Doges** [comment]
no u

**Comment by Doges** [comment]
depois da rola dele, fechando isso.
