### ISSUE TITLE
Ability to disable commands in channels/categories

### ISSUE THREAD

**Issue by LogGame-HU-DEaN** [SwitchbladeBot/switchblade#233]

**Comment by bolsomito** [comment]
wdym? disable certain commands in certain channels or in the entire guild?

**Comment by LogGame-HU-DEaN** [comment]
I think they meant the ability to disable certain commands in certain channels.
![screenshot_20180713142934](https://user-images.githubusercontent.com/35978189/42691896-1c8fba6a-86aa-11e8-9183-4dc98d39c089.png)

**Comment by bolsomito** [comment]
aaaaaaaaah, good riddance, I'll do it in #223 then

**Comment by bolsomito** [comment]
`s!config commands disable <command name>` - disables command x
`s!config commands enable <command name>` - enable command x
`s!config commands list` - lists disabled commands

**Comment by LogGame-HU-DEaN** [comment]
Looks good.
