### ISSUE TITLE
Contador de membros em tempo real

### ISSUE THREAD

**Issue by GamerRanni** [SwitchbladeBot/switchblade#239]
**Sugestão:**
_Um contador de membros no site do Discord que mostra quantos membros tem no exato momento e ao decorrer do tempo se entrar membro ou sair vai atualizando simultaneamente no site, como um contador de inscrições porém para quantidade de membros no Discord_

Exemplo:
![2018-07-16_23-05-02](https://user-images.githubusercontent.com/39033999/42792723-23b0791a-894d-11e8-9cee-abf381d24f7e.gif)

**Comment by Doges** [comment]
sorry, i don't speak Portuguese, marking as invalid

**Comment by davipatury** [comment]
Essa issue deveria estar no [bladey-web](https://github.com/SwitchbladeBot/bladey-web), não?

**Comment by bolsomito** [comment]
@davipatury true
