### ISSUE TITLE
Add an emergency mode with announcements

### ISSUE THREAD

**Issue by Doges** [SwitchbladeBot/switchblade#246]
se der merda, tem ele

**Comment by bolsomito** [comment]
wdym

**Comment by bolsomito** [comment]
be more specific pls

**Comment by pedrofracassi** [comment]
pls specify

**Comment by Doges** [comment]
like, if something happens, will announce to all server owners, and more things

**Comment by Lireoy** [comment]
Isn't this like raid mode?

**Comment by Doges** [comment]
> Isn't this like raid mode?

nah

**Comment by Doges** [comment]
i m telling the bot one, i m closing this one bc i think its useless now
