### ISSUE TITLE
c!whatanime links that are invalid

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#259]
**Bug description**
Bot thinks some links that should be valid, are invalid

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run c!whatanime <OneOfTheLinksBelow>

_Links that don't work_
http://lblend.com/photos/public/img/DSC08195.JPG
https://static.fjcdn.com/pictures/From+acchi+kocchi_abb83d_4937994.png
https://johnjohns1.fjcdn.com/pictures/From+acchi+kocchi_abb83d_4937994.png

This may be a issues on the website's end but should still be noted. If I find more links, I'll comment on this issue

**Expected behavior**
It fetches the image and executes the commannd

**Screenshots**

**Additional context**

**Comment by Doges** [comment]
can reproduce with another photos.

**Comment by Doges** [comment]
@pedrofracassi are you talking with someone?

**Comment by Doges** [comment]
Command removed, archiving.
