### ISSUE TITLE
s!listcord command not responding

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#262]
**Bug description**
Bot starts endlessly typing whenever calling the s!listcord command

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run s!listcord

**Expected behavior**
Should execute the command

**Screenshots**
![](https://puu.sh/B7kdP/370a674477.gif)

**Additional context**

**Comment by bolsomito** [comment]
Ok, I've just figured out that the endpoint that we're trying here does require authentication.

**Comment by bolsomito** [comment]
Fixed as of #265
