### ISSUE TITLE
Support and Crowdin command

### ISSUE THREAD

**Issue by Doges** [SwitchbladeBot/switchblade#285]
/shrug

- [x] Crowdin command - #294

- [ ] Support Command

**Comment by Doges** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support and Crowdin command](https://trello.com/c/CNf0zJre/13-support-and-crowdin-command)

**Comment by Doges** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support and Crowdin command](https://trello.com/c/CNf0zJre/13-support-and-crowdin-command)

**Comment by dpaiv0** [comment]
done
