### ISSUE TITLE
Mute command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#302]
I think it shouldn't be done through roles.

**Comment by Doges** [comment]
what?

**Comment by Doges** [comment]
like, you mean per iD?

**Comment by pedrofracassi** [comment]
We could change the user's permissions instead of giving them a role

**Comment by pedrofracassi** [comment]
Oh shoot, that wouldn't work because Discord doesn't have global user permissions, we'd need to do it per channel

**Comment by Doges** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Moderation Commands](https://trello.com/c/06miAEFM/12-moderation-commands)

**Comment by Doges** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Moderation Commands](https://trello.com/c/06miAEFM/12-moderation-commands)

**Comment by Doges** [comment]
Closing it as this thing exists now
![image](https://user-images.githubusercontent.com/31023616/190489273-fdc6d09e-2b78-4148-9646-f96df7837936.png)
