### ISSUE TITLE
Restrictions to s!rep command

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#332]
There should be a system in place to prevent new discord users to give out rep. People with alt accounts can give rep to themselves and abuse the system. The same goes for the s!pay command. You basically get 2x the s!daily reward and transfer it to your other account with s!pay

**Comment by perronosaurio** [comment]
And what do you recommend to solve this?

**Comment by bolsomito** [comment]
we *could* take it to the next level and embed (for example) `s!daily` to the web, [like Loritta does.](https://loritta.website/us/daily)

**Comment by pedrofracassi** [comment]
I second the account age idea.
