### ISSUE TITLE
s!ping displays negative ping

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#34]
**Bug description**
Sometimes, when executing `s!ping` it displays negative numbers.

**How to reproduce**
1. Run s!ping many times until you get a negative number

**Expected behavior**
Time should be positive

**Screenshots**
![image](https://user-images.githubusercontent.com/25179120/40269898-ae3279a6-5b5a-11e8-9f87-d0d219fec7d6.png)

**Comment by maxrumsey** [comment]
Will look at this tomorrow.

**Comment by davipatury** [comment]
Fix: Use `this.client.ping` instead of calculating the ping manually.

**Comment by pedrofracassi** [comment]
Currently being fixed in #35

**Comment by bolsomito** [comment]
This *may* heve nothing to do with the message ping, as it is more accurate than heartbeat, and that may be because of Discord itself.

**Comment by bolsomito** [comment]
Also, this bug was occuring in between Discord hiccups, so it may have to be with Discord rather than Switchblade, as it is not showing anymore negative ping.

**Comment by pedrofracassi** [comment]
That's true.

**Comment by bolsomito** [comment]
It has been 3 days since no negative ping is showing up, thus I am closing this issue and presumably this was Discord's fault, and not ours.
