### ISSUE TITLE
More image manipulation commands

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#381]
Examples of this can be a deepfry command and a [needs more jpg](http://needsmorejpeg.com/) command

**Comment by bolsomito** [comment]
the 2nd one can be made with `POST https://api.c2g.space/image/jpeg` :mmLol:

**Comment by pedrofracassi** [comment]
Or we could do it ourselves cause depending on APIs SUUUUCKS

**Comment by bolsomito** [comment]
true, [BUT CAN YOU DO THIS](https://github.com/crazy2g/api/tree/master/src/utils/Jimp.js)

**Comment by pedrofracassi** [comment]
Is it doable with canvas?

**Comment by pedrofracassi** [comment]
I've split it into two separate issues so they can be discussed individually. Closing.
