### ISSUE TITLE
"Needs more JPEG" command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#397]
As suggested by @LBlend in #381.

**Comment by pedrofracassi** [comment]
We could reverse engineer [this](http://needsmorejpeg.com/) and use it instead of doing it on the bot's side.

**Comment by pedrofracassi** [comment]
A `POST` request to `http://needsmorejpeg.com/upload` with the image URL as the `image` parameter seems to do it.

**Comment by beescuit** [comment]
IDK if it's the best solution but...
`canvas.toBuffer('image/jpeg', { quality: x })`
quality is a number from 0 (0% quality) to 1 (100% quality)

**Comment by pedrofracassi** [comment]
yeah, I think that works too
