### ISSUE TITLE
The „misc” category is lower case, others are upper case

### ISSUE THREAD

**Issue by LogGame-HU-DEaN** [SwitchbladeBot/switchblade#414]
**Bug description**
The „misc” category is lower case, others are upper case.

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run s!help

**Expected behavior**
The „misc” category should have an uppercase „M”.

**Screenshots**
![c!help](https://user-images.githubusercontent.com/35978189/47522492-011a6080-d896-11e8-8787-3dca7b6b30a6.png)

**Comment by Doges** [comment]
NAB, my fault, i forgot about the general category.

**Comment by Doges** [comment]
fixing it
