### ISSUE TITLE
switchblade.js.org

### ISSUE THREAD

**Issue by MattIPv4** [SwitchbladeBot/switchblade#416]
# JS.ORG CLEANUP
Hello, it seems a `js.org` subdomain that was requested to target this repository (or another on this user/organisation) no longer works.
The subdomain requested was `switchblade.js.org` and had the target of `switchbladebot.github.io/onepage`.
To keep the `js.org` subdomain you should add a page with [reasonable content](https://github.com/js-org/js.org/wiki/No-Content) within a month so the subdomain doesn't resolve to a 404 any longer.
Otherwise the requested subdomain will be removed from JS.ORGs zonefile and the list of active subdomains.

**If you are wanting to keep the `js.org` subdomain and have added [reasonable content](https://github.com/js-org/js.org/wiki/No-Content), YOU MUST reply to the [main cleanup issue](https://github.com/js-org/js.org/issues/2455) with the response format detailed at the top to keep the requested subdomain.**

**Comment by Doges** [comment]
Hello! We archived the onepage repository and we already got the new domain, thanks for contacting us, we forgot the domain, and we are not using the js.org for a while, so, feel free to remove it! Thanks.
