### ISSUE TITLE
"s!samp help" causes an error

### ISSUE THREAD

**Issue by Tsugami** [SwitchbladeBot/switchblade#424]
![image](https://user-images.githubusercontent.com/32089154/47860406-5b607780-dde8-11e8-82d3-f5792e9ee30e.png)

**Comment by Doges** [comment]
use s!help samp smh

**Comment by bolsomito** [comment]
I'm not 100% sure if this is an actual bug, since it's supposed to be used as `s!help samp`

**Comment by pedrofracassi** [comment]
Why did we close this? The error should be handled, and something like "You need to give me a valid IP address" should be displayed.

AddressParameter when

**Comment by perronosaurio** [comment]
ok

**Comment by Doges** [comment]
@pedrofracassi thats kinda impossible, because IP addresses its only numbers and dots, what about the alphanumeric addresses?

**Comment by Doges** [comment]
we can try to add a try and catch for this.

**Comment by pedrofracassi** [comment]
They have at least one dot, that's for sure

**Comment by Doges** [comment]
an address parameter to find a dot? are you fucking kidding me
