### ISSUE TITLE
Steam Ladder commands

### ISSUE THREAD

**Issue by LogGame-HU-DEaN** [SwitchbladeBot/switchblade#443]
This API came out a couple of minutes ago, you can check Steam profile rankings, (Total XP, Games, Badges, Steam Age, Playtime) and you can see rankings in different regions and with ISO 3166-1 alpha-2 country codes too.

https://steamladder.com/user/settings/api/
https://github.com/bommels/steamladder-api-examples

**Comment by pedrofracassi** [comment]
What commands would be nice?

**Comment by LogGame-HU-DEaN** [comment]
s!sl (top)/<xp/games/badges/playtime/age> <country/region or blank for worldwide>
s!sl  (profile) <SteamID64

Stuff in brackets could be optional.

**Comment by pedrofracassi** [comment]
Working on it!
