### ISSUE TITLE
README.md images not displaying

### ISSUE THREAD

**Issue by LogGame-HU-DEaN** [SwitchbladeBot/switchblade#45]
**Bug description**
Both images in the README.md file in not displaying, gives a „Cannot proxy the given URL” error.

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Open the README.md file.

**Expected behavior**
The images should be displayed.

**Comment by LogGame-HU-DEaN** [comment]
Update: Second image is also borked now.

**Comment by pedrofracassi** [comment]
Seems fine to me. @bolsomito mentioned it being a problem with his AWS S3 box. Is it fixed?

**Comment by LogGame-HU-DEaN** [comment]
Looks fine to me too now, shall I close?

**Comment by pedrofracassi** [comment]
Seems to be fixed. Closing.
