### ISSUE TITLE
Add a "skip to" command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#456]
`s!skipto<song index>` would skip to a specific song on the playlist, removing everything before it.

**Comment by davipatury** [comment]
Maybe `s!queue jumpto <index>` or `s!queue skipto <index>`? Or you want it to be a new command?

**Comment by pedrofracassi** [comment]
`s!queue jumpto <index>` seems good for me. `skipto` could be an alias too.

**Comment by pedrofracassi** [comment]
But hey, skipping puts the current song back into the queue?

**Comment by davipatury** [comment]
No.
