### ISSUE TITLE
Add a flag to s!play to search on SoundCloud instead of youtube

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#457]
`s!play darude sandstorm --soundcloud` (maybe `--sc` too!)

**Comment by davipatury** [comment]
I think you can use `s!play scsearch:darude sandstorm`, but a flag is probably better.

**Comment by pedrofracassi** [comment]
Seems quite easy to do, then. Just add `scsearch:` to the query if the flag is present.
