### ISSUE TITLE
Add a seek command to let users jump time in a song

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#461]
`s!seek 10` - Jumps 10 seconds
`s!seek -10` - Jumps 10 seconds **backwards**
`s!seek 1:25` - Jumps **to** 1'25" seconds on the current song

**Comment by davipatury** [comment]
Any tips about the time parsing? Should I just look for a `:` in the parameter?

**Comment by justandras** [comment]
Don't forget that they could listen to mixes which could exceed one hour, so you need to implement hours too.
