### ISSUE TITLE
Add service icons to the now playing image

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#466]
![image](https://user-images.githubusercontent.com/25179120/48513176-52d55b80-e842-11e8-8549-7296d58b8542.png)

**Comment by pedrofracassi** [comment]
@willianrod

**Comment by dpaiv0** [comment]
services that we use:
+ spotify
+ youtube
+ soundcloud
+ deezer
+ HTML
+ twitch
+ mixer

what more?

**Comment by metehus** [comment]
> services that we use:
> 
> * spotify
> * youtube
> * soundcloud
> * deezer
> * HTML
> * twitch
> * mixer
> 
> what more?

excuse me HTML?

**Comment by Doges** [comment]
yes, html

**Comment by justandras** [comment]
Shouldn't you call that HTTP?

**Comment by metehus** [comment]
> Shouldn't you call that HTTP?

^

**Comment by metehus** [comment]
> yes, html

`s!play <song><name>desça dai seu corno</name></song>`

**Comment by dpaiv0** [comment]
YOU CAN SUCK MY FUCKING DICK

**Comment by perronosaurio** [comment]
> YOU CAN SUCK MY FUCKING DICK

i can do this

**Comment by metehus** [comment]
@perronosaurio me too

**Comment by Doges** [comment]
> Shouldn't you call that HTTP?

yea, http
