### ISSUE TITLE
If prefix is set to a special character, the bot responds to all of them.

### ISSUE THREAD

**Issue by LogGame-HU-DEaN** [SwitchbladeBot/switchblade#472]
**Bug description**
If the bot's prefix is set to a special character, for example, „.”, the bot will respond to any special character prefix, for example „"” and „ü”.

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Set the bot's prefix to a special character.
2. Try to run a command with a different special character as the prefix.

**Expected behavior**
The bot should only respond to the set prefix.

**Screenshots**
![screenshot_20181118091919](https://user-images.githubusercontent.com/35978189/48670152-0d9b7d00-eb13-11e8-8528-a85ca3165e0a.png)

**Comment by bolsomito** [comment]
Can reproduce. ![bug](https://my.mixtape.moe/gmocit.png)

**Comment by Doges** [comment]
thats due the regex on prefix

**Comment by pedrofracassi** [comment]
what can we do to fix it?

**Comment by Doges** [comment]
change the mention regex from mainlistener
