### ISSUE TITLE
Reverse text command

### ISSUE THREAD

**Issue by ImGabe** [SwitchbladeBot/switchblade#478]
https://github.com/ImGabe/ElyxBot/blob/master/comandos/flip.js

**Comment by pedrofracassi** [comment]
Reverse?

**Comment by ImGabe** [comment]
Yeah, sorry.

**Comment by pedrofracassi** [comment]
This one is suuuuper easy to do. Any of the new guys wanna try?

**Comment by pedrofracassi** [comment]
You can make it based on [the source code for clapify](https://github.com/SwitchbladeBot/switchblade/blob/8599bb8f903f473b8241cf46a95177cf06286a4f/src/commands/memes/clapify.js)
