### ISSUE TITLE
Bot won't let you queue if it's in a channel it couldn't normally join

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#481]
**How to reproduce**
Steps to reproduce the unusual behavior:
1. Go to a channel the bot **can** join
2. Start playing something with `s!play`
3. Move the bot to a channel it can't join normally
4. Try to queue something with `s!play`

**Expected behavior**
Bot should queue the song normally, as it's already playing something else

**Screenshots**
![image](https://user-images.githubusercontent.com/25179120/48680643-3c057080-eb84-11e8-96dd-f7b396830432.png)

**Comment by pedrofracassi** [comment]
@Doges <3

**Comment by Doges** [comment]
![](https://i.imgur.com/oNwtbAK.png) @pedrofracassi <3

**Comment by pedrofracassi** [comment]
Don't
