### ISSUE TITLE
Presidential Alert image generator command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#496]
`s!presidentialalert <text>`

![Example](https://preview.redd.it/9omfu3f6k0q11.jpg?auto=webp&s=384d406b987f55251be7d267da24adaf7cde2a16)

Template: https://i.imgur.com/Zfnv5eg.jpg

Font is San Francisco, but can be easily replaced by Helvetica Neue.

**Comment by bolsomito** [comment]
why should we replace the font to Helvetica Neue if SF is free to download?

**Comment by bolsomito** [comment]
just use San Francisco smh

**Comment by Doges** [comment]
> why should we replace the font to Helvetica Neue if SF is free to download?

san francisco is free too

**Comment by Doges** [comment]
![](https://i.imgur.com/H9fGLAp.jpg)

**Comment by pedrofracassi** [comment]
Oh, I thought SF was paid and Helvetica was free

**Comment by pedrofracassi** [comment]
Who's working on this one?

**Comment by Doges** [comment]
i can provide the font, but idk how to use canvas :hahaa:

**Comment by pedrofracassi** [comment]
It should be pretty easy to do. Can you create a branch for this and add the font to `/assets`?

**Comment by Doges** [comment]
sure

**Comment by pedrofracassi** [comment]
I'm on it.
