### ISSUE TITLE
Add a Patreon in s!bi

### ISSUE THREAD

**Issue by ImGabe** [SwitchbladeBot/switchblade#499]
![image](https://user-images.githubusercontent.com/24387926/48980377-3e4d5a80-f0af-11e8-9c5e-acf0ee9213e7.png)
Icon: ![image](https://vignette.wikia.nocookie.net/logopedia/images/5/51/Patreon_%28icon%29.png/revision/latest/scale-to-width-down/240?cb=20161024222125)
Text: Donate to Me

Something like this would be good.

**Comment by pedrofracassi** [comment]
JESUS FUCKING CHRIST THAT'S A HUGE ICON

**Comment by ImGabe** [comment]
> JESUS FUCKING CHRIST THAT'S A HUGE ICON

Is it that big?
![image](https://user-images.githubusercontent.com/24387926/49050530-f15ea680-f1ca-11e8-985d-0535abaa3368.png)

**Comment by pedrofracassi** [comment]
> Is it that big?

no xD

I was talking about the image embedded on github
