### ISSUE TITLE
s!time to fix this

### ISSUE THREAD

**Issue by justandras** [SwitchbladeBot/switchblade#502]
**Bug description**
The time command doesn't work with places

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run s!time <place>

**Expected behavior**
The TikTok mechanism in bladey tells you the time.

**Screenshots**
![image](https://user-images.githubusercontent.com/32372119/49094472-a7c39980-f266-11e8-9e59-1e9eb5324d08.png)

**Additional context**
A D D I T I O N A L   C O N T E X T

**Comment by Doges** [comment]
intended, you need to give an Iana tz format

**Comment by pedrofracassi** [comment]
We can use Google Map's Geocoding and Timezone APIs to accept city names instead. Waaaay more user friendly.

**Comment by pedrofracassi** [comment]
https://developers.google.com/maps/documentation/geocoding/start

https://developers.google.com/maps/documentation/timezone/intro

**Comment by pedrofracassi** [comment]
@metehus' Weather command PR (#498) has a GMaps wrapper already. We can get to work on that after it gets merged.

**Comment by Doges** [comment]
so open another ticket or change the title

**Comment by pedrofracassi** [comment]
We can keep this one.

**Comment by metehus** [comment]
We can use moment timezone with the GMaps API to get the locale
