### ISSUE TITLE
Make codacy ignore the test folder

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#506]
Currently, all of our codacy issues come from the `test` folder, due to undefined functions (that are actually defined by mocha, but not in those files): https://app.codacy.com/app/bolsomito/switchblade/issues/index

An easy fix would be to ignore everything inside `test`.

https://support.codacy.com/hc/en-us/articles/360005097654-Ignore-files-from-Codacy-analysis

**Comment by Doges** [comment]
Did it on commit af988be
