### ISSUE TITLE
Fetch required emoji from emoji guilds

### ISSUE THREAD

**Issue by dpaiv0** [SwitchbladeBot/switchblade#511]
I know this is kinda stupid, but stick with me:

+ Switchblade has an emoji guild, that has emojis that Switchblade needs to use
+ Switchblade fetches it (or them, if more than 1) and stores it in `this.client.emojis`
+ When needed to use a certain emoji, use `this.client.emojis.PatreonLogo`

Known snippet that can help:
```js
const emojiGuilds = process.env.EMOJI_GUILDS && process.env.EMOJI_GUILDS.split(',')
for (var i in emojiGuilds) {
  const guildEmojis = emojiGuilds[i].emojis
  for (var int in guildEmojis) {
    this.emojis.push(guildEmojis[int])
  }
}
```

**Comment by pedrofracassi** [comment]
We could actually pass the `emojis` object through CommandContext.

**Comment by pedrofracassi** [comment]
Actually, I think it should be a function, so it handles missing emoji gracefully

**Comment by pedrofracassi** [comment]
`emoji('PatreonLogo')` when

**Comment by pedrofracassi** [comment]
I'll get to work on this during the next week. Remindme.

**Comment by dpaiv0** [comment]
will *try* to do this
