### ISSUE TITLE
BeatSaver command is not responding anymore

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#517]
**Bug description**
The beat saver command is not responding. It just types forever.

**How to reproduce**
1. Type `s!beatsaver ttfaf`

**Expected behavior**
The bot should send an embed with the song's information

**Comment by pedrofracassi** [comment]
```
Dec 01 11:37:00 switchblade-production app/worker.1: [ErrorLog] { Error: 404 Not Found 
```

Seems to be a 404. Something changed with BeatSaver's website.

**Comment by bolsomito** [comment]
you did the command, so you fix

**Comment by bolsomito** [comment]
>:)

**Comment by Doges** [comment]
^

**Comment by metehus** [comment]
^

**Comment by Doges** [comment]
API changed, we can't search by the name anymore.

**Comment by pedrofracassi** [comment]
Hmmk. I'll investigate.
