### ISSUE TITLE
Ship command from Baba

### ISSUE THREAD

**Issue by perronosaurio** [SwitchbladeBot/switchblade#535]

**Comment by perronosaurio** [comment]
![image](https://user-images.githubusercontent.com/27968093/49342351-b5936900-f630-11e8-9a38-6a7f328ad113.png)

**Comment by pedrofracassi** [comment]
oof

**Comment by Doges** [comment]
how we can do this?, the name thingy

**Comment by davipatury** [comment]
```js
name1.substr(0, name1.length * 0.5) + name2.substr(name2.length * 0.5);
```

**Comment by pedrofracassi** [comment]
Looks good. Can we do it with canvas and an embed?

**Comment by perronosaurio** [comment]
> Looks good. Can we do it with canvas and an embed?

sure
