### ISSUE TITLE
All Baba's NSFW commands

### ISSUE THREAD

**Issue by perronosaurio** [SwitchbladeBot/switchblade#537]
![image](https://user-images.githubusercontent.com/27968093/49342390-3488a180-f631-11e8-94e4-5d72a708268d.png)

**Comment by pedrofracassi** [comment]
Where is each of them pulled from?

**Comment by pedrofracassi** [comment]
If reddit, we can use `RandomRedditPostCommand`

**Comment by perronosaurio** [comment]
From subreddits

**Comment by Doges** [comment]
just ignore the trap command <

**Comment by Doges** [comment]
:hahaa: #591

**Comment by justandras** [comment]
don't

**Comment by Doges** [comment]
> don't

i already tried

**Comment by Doges** [comment]
look at #486

**Comment by justandras** [comment]
OwO does this mean s!trap?

**Comment by Doges** [comment]
yes
