### ISSUE TITLE
Twitch user info

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#548]
**Is your feature request related to a problem? Please describe.**
I would like to check user info for twitch profiles because... why not? ¯\_(ツ)_/¯

**Describe the solution you'd like**
It should contain
- Link to profile
- Bio
- Followcount
- User creation date
- Twitch profile picture
**If the user is live**
- Stream title
- Game being streamed
- Viewercount

**Additional context**
Made one myself using the twitch API in python. Use this as an inspiration
http://iamavirg.in/58cc5c9268c.png

**Comment by pedrofracassi** [comment]
`s!twitch <username>`?
