### ISSUE TITLE
s!clear 

### ISSUE THREAD

**Issue by justandras** [SwitchbladeBot/switchblade#552]
**Is your feature request related to a problem? Please describe.**
after adding a playlist it's hard to skipp the songs when we get bored of it.

**Describe the solution you'd like**
add votes to s!stop or add s!clear that would empty the queue except the one that's playing

**Describe alternatives you've considered**
ban doges

**Additional context**
![image](https://user-images.githubusercontent.com/32372119/50018068-61906900-ffce-11e8-97fd-98e4cf3551b3.png)

**Comment by ndr3w221** [comment]
s!clear should be a command that clears a channel of messages
maybe s!clearqueue

**Comment by pedrofracassi** [comment]
Hmm, that's a conflict I didn't think about. Maybe s!purge for channels, and s!clear for music?

**Comment by davipatury** [comment]
Maybe create a subcommand in `s!queue`, something like `s!queue clear`?

**Comment by Doges** [comment]
nah, a new command is better

**Comment by justandras** [comment]
I like davis idea better

**Comment by pedrofracassi** [comment]
We gotta think about what's easier for the end user. What will they think first when trying to clear the queue?

**Comment by justandras** [comment]
add this line to the queue embed: 

> To clear the queue use the `prefix queue clear` command.

**Comment by pedrofracassi** [comment]
That sounds good to me.
