### ISSUE TITLE
Discord Bot list vote link

### ISSUE THREAD

**Issue by justandras** [SwitchbladeBot/switchblade#554]
**Is your feature request related to a problem? Please describe.**

both. "because I have to wait for dbl to catch up I always forget to write s!dbl the second time" -Lblend 2018

**Describe the solution you'd like**

Returns an embed with the link for voting

**Describe alternatives you've considered**

s!dblink s!discordbotlistlink s!dbll

**Additional context**

![image](https://user-images.githubusercontent.com/32372119/50048314-232ba480-00c9-11e9-82b0-7ff6b92303ad.png)

**Comment by Doges** [comment]
The bug is won't fix, because that's a dbl issue, not ours.

**Comment by pedrofracassi** [comment]
Still, we could do something to make the experience better for our users

**Comment by justandras** [comment]
@Doges read it again. I wasn't asking for a fix I was asking for a way to get the link without googleing for it everytime.

**Comment by Doges** [comment]
> Yeah, but the requesr makes the api cache that we didn't vote. I am asking for a simple ping level command in terms of difficulty. You could have written it in the time you spent on arguing.

like, i m testing the dbl api in postman (with no cache), actually, its a dbl issue, we can do a function to recheck the votes

**Comment by justandras** [comment]
How about in the main time you make a static command that returns the link?

**Comment by Doges** [comment]
wait, what you're talking about the return the url, can you send an example?

**Comment by Doges** [comment]
> but the problem is that that command makes the api cache.

actually, it doesn't

**Comment by Doges** [comment]
its the dbl api problem, not a cache problem

**Comment by dpaiv0** [comment]
This will be fixed as of #596, since we'll be using Webhooks to handle DBL votes
