### ISSUE TITLE
Add a days since joined/created counter to userinfo and guildinfo command

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#558]
**Describe the solution you'd like**
Add a days since joined/created counter to userinfo and guildinfo command

Can be achieved by subtracting the datetime of the command message with the guild/user creation/join date
example in python:
`(ctx.message.created_at - guild.created_at).days`

**Additional context**
http://iamavirg.in/e07d9ed2c6d.png

**Comment by dpaiv0** [comment]
tbc aswell on #599
