### ISSUE TITLE
Add member number to userinfo command

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#559]
**Describe the solution you'd like**
Sort the members by the date they joined the guild that command is executed in. Index them. 

**Additional context**
http://iamavirg.in/a1eba6145b0.png

**Comment by Doges** [comment]
that's kinda hard because the bot will only count after he gets added in the server

**Comment by pedrofracassi** [comment]
No? The API does return a timestamp that tells you when the member joined that guild. We could use it to sort the users. Would get tricky for larger guilds, doe.

**Comment by LBlend** [comment]
Well the bot I took the screenshot of is running on a server with 3.5K members and is using this lambda function to calculate it. It's really fast. Dunno about the "the bot will only count after he gets added in the server" though
`sorted(guild.members, key=lambda m: m.joined_at).index(user) + 1`

**Comment by dpaiv** [comment]
through testing, I came up with this:
```message.guild.members.sort(m => m.joinedTimestamp).map(m => m).indexOf(<GuildMember>) + 1
```

**Comment by dpaiv** [comment]
^^^^^^
forget this
`message.guild.members.sort((a, b) => a.joinedTimestamp - b.joinedTimestamp).map(m => m).indexOf(<GuildMember>) + 1`

**Comment by dpaiv0** [comment]
tbc aswell on #599
