### ISSUE TITLE
Some commands don't startTyping, but do stop.

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#566]
`handshake`, `hug`, `kiss`, `pat` and `slap` don't startTyping, but do stop after the message is sent.

We might want to check for other commands that might be doing the same.

**Comment by LogGame-HU-DEaN** [comment]
`triggered.js` and `nowplaying.js` don't have startTyping either, but do have stopTyping. I'm not really sure if those need it, though.
Others are fine.

**Comment by davipatury** [comment]
Both need it cause they have image manipulation.
