### ISSUE TITLE
Problems on playong soundcloud music

### ISSUE THREAD

**Issue by metehus** [SwitchbladeBot/switchblade#592]
![Error screenshot](https://i.imgur.com/HEuy7N3.jpg)
# Bug description 
Error on displaying the track cover, leading to an erro on the music playback
# How reproduce
ps. the screenshot isnt mine so i cant tell details
Play a soundcloud music
# Expected behaviour
Displaying the track cover and playing the music fisplaying no errors

**Comment by davipatury** [comment]
Probably it's cause the track is [private](https://soundcloud.com/dancko/kareles-hellss-gate-original/s-D7Yxs?in=dancko/sets/distopia-ep/s-HHaLK).
Working on a fix right now.
