### ISSUE TITLE
Fix "similar-code" issue in src/commands/memes/thinking.js

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#6]
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/SwitchbladeBot/switchblade/src/commands/memes/thinking.js#issue_5afa23e93b6dcd0001000026

**Comment by pedrofracassi** [comment]
I suggest making an utils folder and adding a reddit.js file with methods for getting posts.

**Comment by bolsomito** [comment]
Fixed as of #10.
