### ISSUE TITLE
Add thousand separators to botinfo numbers according to the locale

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#601]
![image](https://user-images.githubusercontent.com/25179120/51655267-0a919280-1f83-11e9-88e7-2e7125e39bd7.png)

**Comment by dpaiv0** [comment]
We should implement this as a util, something like ```js
<NumberUtils>.format(language, value)
```

**Comment by dpaiv0** [comment]
PS: This is getting closed aswell on #599
