### ISSUE TITLE
Some spotify songs throw errors

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#607]
```
TypeError: (intermediate value) is not iterable 
      at Function.provideTrack (/app/src/music/sources/spotify/SpotifySongSource.js:52:26) 
     at process._tickCallback (internal/process/next_tick.js:68:7)
```

![image](https://user-images.githubusercontent.com/25179120/51765291-15007900-20b6-11e9-8462-f843dd702e7a.png)

### URLs known to cause this issue:
- https://open.spotify.com/track/2YJkCOKWnRrAcKOzlqIujo?si=H_7DEWPrQ1iOnQC4jCN6mg

**Comment by davipatury** [comment]
Weird, I can't reproduce this issue with my instance, only with Canary and stable versions.
