### ISSUE TITLE
Cannot destructure property `body` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#610]
```
[ErrorLog] Error: Lavalink fetchTracks Error: 503 Service Unavailable
      at snekfetch.get.query.set.catch.e (/app/src/music/SwitchbladePlayerManager.js:54:30)
      at process._tickCallback (internal/process/next_tick.js:68:7)
[ErrorLog] TypeError: Cannot destructure property `body` of 'undefined' or 'null'.
      at Map.fetchTracks (/app/src/music/SwitchbladePlayerManager.js:57:22)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

![image](https://user-images.githubusercontent.com/25179120/51782000-fe7f0f80-20ff-11e9-8599-d078978ad959.png)

### Songs known to cause this issue
 - https://www.youtube.com/watch?v=zJ3qtWOz9tE"

### What we know so far
- The bot seems to take a long time to start playing but eventually does.
- Doesn't really seem to be caused by that song. Saw it occur after a queue ended too.
- Might be a snekfetch problem
- [Happened in production too](https://i.imgur.com/tyg3jkB.png)

**Comment by davipatury** [comment]
I guess it was a Lavalink server error. Can we close this?

**Comment by pedrofracassi** [comment]
Yes. A server restart fixed it.
