### ISSUE TITLE
s!top not working anymore

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#611]
```
[ErrorLog] Error: Server responded with 404 
```

![image](https://user-images.githubusercontent.com/25179120/51782543-df38b000-2108-11e9-8b89-098111dad32f.png)

**Comment by davipatury** [comment]
Temporarily fixed.

**Comment by LogGame-HU-DEaN** [comment]
Apparently it works now, not sure why.

**Comment by pedrofracassi** [comment]
Well, if an account gets deleted from discord we should also delete it from our records

**Comment by davipatury** [comment]
We don't, we need to use `.catch()` on the `Image.from` Promise.

**Comment by pedrofracassi** [comment]
Has this been fixed?

**Comment by davipatury** [comment]
Not really. The code is still the same, there's no fallback image.

**Comment by pedrofracassi** [comment]
Can we use a default blurple image as the fallback?

**Comment by davipatury** [comment]
Yes, working on It.

**Comment by dpaiv0** [comment]
what about the user's tag?
