### ISSUE TITLE
Example usage for commands

### ISSUE THREAD

**Issue by perronosaurio** [SwitchbladeBot/switchblade#613]
Usage: s!help [command name]
Aliases: commands, ajuda
Example usage: s!help ping

**Comment by zerinho6** [comment]
It should also show a image of someone using the command. (With the default prefix)

Like this:

![](https://cdn.discordapp.com/attachments/356270085566103563/538895363881566209/unknown.png)

**Comment by perronosaurio** [comment]
wht not

**Comment by Doges** [comment]
> It should also show a image of someone using the command. (With the default prefix)
> 
> Like this:
> 
> ![](https://camo.githubusercontent.com/27fad6883b5d096ad706b183d698ea67eb577ff0/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3335363237303038353536363130333536332f3533383839353336333838313536363230392f756e6b6e6f776e2e706e67)

no

**Comment by metehus** [comment]
> It should also show a image of someone using the command. (With the default prefix)
> 
> Like this:
> 
> ![](https://camo.githubusercontent.com/27fad6883b5d096ad706b183d698ea67eb577ff0/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3335363237303038353536363130333536332f3533383839353336333838313536363230392f756e6b6e6f776e2e706e67)

no

**Comment by Doges** [comment]
Not possible/already possible due the new discord api
