### ISSUE TITLE
You can go to a negative part of a song using c!seek

### ISSUE THREAD

**Issue by LogGame-HU-DEaN** [SwitchbladeBot/switchblade#616]
**Bug description**
You can go to a negative part of a song using c!seek.

**How to reproduce**
1. Run c!seek -30 when the song just started.

**Expected behavior**
The bot should give an error.

**Screenshots**
![screenshot_20190127195133](https://user-images.githubusercontent.com/35978189/51805415-1aec8a80-226d-11e9-8d24-4a99deaf74d3.png)

**Comment by dpaiv0** [comment]
Understood what happens here. Will fix.
