### ISSUE TITLE
c!seek can't always go to end of song

### ISSUE THREAD

**Issue by LogGame-HU-DEaN** [SwitchbladeBot/switchblade#617]
**Bug description**
c!seek can't always go to end of song.

**How to reproduce**
1. Run c!seek to go to the end of a song
2. Run on another song.

**Expected behavior**
The playback should go to the end of the song.

**Screenshots**
![screenshot_20190127200125](https://user-images.githubusercontent.com/35978189/51805515-82570a00-226e-11e9-94bb-cea4958c842f.png)

**Comment by dpaiv0** [comment]
CNR, is this specific to any platform? (spotify, soundcloud, youtube..?)

**Comment by davipatury** [comment]
The problem is: the "real" (from the API) song duration is 2 minutes and 51.875 seconds which is lower than 2 minutes and 52 seconds.
