### ISSUE TITLE
Bug in DBL command

### ISSUE THREAD

**Issue by tra4in** [SwitchbladeBot/switchblade#618]
**Bug description**
When executing the command * * DBL * * It automatically gives 1k200 of coins even not having voted...

**How to reproduce**
1. Run c!dbl

**Expected behavior**
When the person has voted he gives you a certain reward

**Screenshots**
http://prntscr.com/mcx3rk

**Comment by Doges** [comment]
intended, canary has the same token as stable

**Comment by dpaiv0** [comment]
no, it's not intended. i know the bug, unclose this shit

**Comment by dpaiv0** [comment]
also: it's related to #619
