### ISSUE TITLE
Jumping to a song while playback is looped removes the songs before the song oneself jumped to

### ISSUE THREAD

**Issue by LogGame-HU-DEaN** [SwitchbladeBot/switchblade#623]
**Bug description**
Jumping to a song while playback is looped removes the songs before the song oneself jumped to.

**How to reproduce**
1. Add songs to the queue.
2. Start looping playback with c!loop.
3. Jump to a song using c!queue jump <number>.

**Expected behavior**
The songs should stay.

**Screenshots**
![screenshot_20190127224017](https://user-images.githubusercontent.com/35978189/51807218-90b02080-2284-11e9-8b4d-6c6e97cf7576.png)

**Comment by Doges** [comment]
CNR on youtube
