### ISSUE TITLE
c!queue subcommand strings are displaying as undefined

### ISSUE THREAD

**Issue by LogGame-HU-DEaN** [SwitchbladeBot/switchblade#624]
**Bug description**
c!queue subcommand strings are displaying as undefined.

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run c!queue remove or c!queue jump

**Expected behavior**
The strings (if there are any) should display correctly.

**Screenshots**
![screenshot_20190127224222](https://user-images.githubusercontent.com/35978189/51807264-2d72be00-2285-11e9-99ab-a1189230d9c5.png)

**Comment by Doges** [comment]
CR
