### ISSUE TITLE
Command flags in s!help [command]

### ISSUE THREAD

**Issue by perronosaurio** [SwitchbladeBot/switchblade#627]

**Comment by pedrofracassi** [comment]
We'd need descriptions for each flag, tho.

**Comment by metehus** [comment]
we can do in help something like
**Flags:** `flag1`, `flag2`
and when use the help with `--flags` it shows the flags and the description

**Comment by pedrofracassi** [comment]
We should do something like

**Flags:**
`--flag1` - Description 1
`--flag2` - Description 2

(and then the subcommands would follow the same idea)

**Comment by metehus** [comment]
@pedrofracassi you say this for the --flags right?

**Comment by Doges** [comment]
no need to due slash commands
