### ISSUE TITLE
Surrounding links with <> doesn't work correctly in s!play

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#646]
If you add `<>` around a link, it plays a different video

**Comment by dpaiv0** [comment]
`.replace(/<>/g, '')`

**Comment by Doges** [comment]
cannot reproduce i think

**Comment by Doges** [comment]
OH NEVERMIND

**Comment by Doges** [comment]
![](https://i.imgur.com/ZR9UDHb.png)
