### ISSUE TITLE
s!queue jump not working correctly

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#647]
![image](https://user-images.githubusercontent.com/25179120/52105539-2e358800-25d6-11e9-983a-189b0d918ca6.png)

**Comment by davipatury** [comment]
[We must use `>` instead of `>=`](https://github.com/SwitchbladeBot/switchblade/blob/dev/src/music/structures/GuildPlayer.js#L99)

**Comment by davipatury** [comment]
Fixed by 8f615a64ae3ce3d27f8bad49eed167ea357e5c1c
