### ISSUE TITLE
Short songs don't play fully everytime

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#648]
An user reported that playing https://www.youtube.com/watch?v=VSNxlBZ--3Y cuts the first seconds of the song before it starts playing

(Might be a lavalink problem tho)

**Comment by Aericio** [comment]
Correction:

It cuts off at the LAST second of the song, then ends. It isn't an issue if the song is looped OR if there is a song after it.

**Comment by pedrofracassi** [comment]
Hmm, that's weird. Maybe that doesn't happen when in a loop because of cache?

**Comment by pedrofracassi** [comment]
Is the bot disconnecting before the song ends?

**Comment by Doges** [comment]
I'm pretty sure that's already fixed then i'm closing the issue

**Comment by Aericio** [comment]
nice
