### ISSUE TITLE
haveibeenpwned.com lookup command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#658]
The command would let users check if their emails or usernames have been pwned.

https://www.npmjs.com/package/hibp
https://haveibeenpwned.com/API/v2

**Comment by Doges** [comment]
hey, give me your password to see if you got pwned.

 ik thats from email, not passwd

_Sent from my HP LaserJet Enterprise MFP M525f using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dpaiv0** [comment]
doing atm
