### ISSUE TITLE
Lucky on search command

### ISSUE THREAD

**Issue by metehus** [SwitchbladeBot/switchblade#664]
**Describe the solution you'd like**
when use `--lucky` or `--first` on a SearchCommand it shows the first result

**Describe alternatives you've considered**
In the structure make custom flags support together with the lucky

**Comment by Doges** [comment]
like this one? ![](https://i.imgur.com/oYcolXZ.png)

**Comment by metehus** [comment]
@Doges yes

_Sent from my Galaxy J7 Prime using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Doges** [comment]
@metehus okay.

_Sent from my HP LaserJet Enterprise MFP M525f using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
