### ISSUE TITLE
Subcommands load errors

### ISSUE THREAD

**Issue by metehus** [SwitchbladeBot/switchblade#667]
**Bug description**
When i try to start the bot, it gives a load error when loading a subcommand that the parent command cant load(because of a requeriment of an api for example)

**How to reproduce**
1. Create a command that cant load, an api requeriment without the api on env vars for example
2. Create a subcommand with the parent command as the last step
3. Start the bot

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/22124518/52299644-1743bc80-296d-11e9-9a4b-43373f5e3bab.png)

**Comment by Doges** [comment]
can reproduce, it happens with me

**Comment by pedrofracassi** [comment]
Can reproduce too.

**Comment by Doges** [comment]
F
