### ISSUE TITLE
Some markdown messages in description

### ISSUE THREAD

**Issue by metehus** [SwitchbladeBot/switchblade#673]
In mobile some messages on the embed title with markdown doesnt work, like this screenshot:
![](https://i.imgur.com/MPGf8nq.jpg)
It would be more easy to put these messages into the description because they accept markdown in mobile

_Sent from my Galaxy J7 Prime using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Lireoy** [comment]
Samsung Galaxy A7 2015 - Discord 8.4.5G - I don't have any issues with markdown nor in messages nor embeds.

**Comment by dpaiv0** [comment]
ZTE Blade L5 Plus - Discord 8.4.2G - CR

**Comment by pedrofracassi** [comment]
CR means Cannot Reproduce or Can Reproduce?

**Comment by Doges** [comment]
> CR means Cannot Reproduce or Can Reproduce?

cnr = cannot, cr = can

**Comment by dpaiv0** [comment]
^

**Comment by pedrofracassi** [comment]
Let's get this sorted out. We first need to find all embeds where this happens.

**Comment by metehus** [comment]
it only happens on embeds with markdown on title

**Comment by davipatury** [comment]
He knows it, but which commands use markdown in the embed's title?

**Comment by Doges** [comment]
working on a fix, i m changing to setdescription

**Comment by Doges** [comment]
nevermind, cannot reproduce it anymore, CNR Android Alpha 8.7.0 Zenfone 3 ZEK20KL 5.2" Android 8.1. ![](https://media.discordapp.net/attachments/259345954811936791/568883297036271627/Screenshot_20190419-163807.png)
