### ISSUE TITLE
Mixer nowplaying

### ISSUE THREAD

**Issue by metehus** [SwitchbladeBot/switchblade#679]
![image](https://user-images.githubusercontent.com/22124518/52538362-d840ad00-2d58-11e9-9031-99969ad44d4e.png)

**Comment by Doges** [comment]
wait, we accept mixer?

_Sent from my HP LaserJet Enterprise MFP M525f using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by metehus** [comment]
@Doges actually yes


_Sent from my LG smart tv using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
