### ISSUE TITLE
Use Probot on github

### ISSUE THREAD

**Issue by Doges** [SwitchbladeBot/switchblade#682]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

https://github.com/probot/probot

**Describe alternatives you've considered**

**Additional context**

_Sent from my HP LaserJet Enterprise MFP M525f using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImGabe** [comment]
Nice idea

**Comment by Doges** [comment]
pedro is gay?
/polls yes

**Comment by Doges** [comment]
should i ban myself

/polls yes ok yep

**Comment by Doges** [comment]
done
