### ISSUE TITLE
Mention prefix doesn't work if the bot has a nickname

### ISSUE THREAD

**Issue by perronosaurio** [SwitchbladeBot/switchblade#688]
![image](https://user-images.githubusercontent.com/27968093/52858669-2d861100-3101-11e9-8f91-f519db03d9c1.png)

**Comment by pedrofracassi** [comment]
Updated title.

**Comment by davipatury** [comment]
Fixed by 866d84e9b16e3f47d2b13a530e36048bb9cf8e1e
