### ISSUE TITLE
SearchCommand doesn't handle errors

### ISSUE THREAD

**Issue by Doges** [SwitchbladeBot/switchblade#696]
**Bug description** 
SearchCommand doesn't handle errors

**How to reproduce** 
force an error on searhccommand

**Expected behavior** 
handle the error

**Comment by metehus** [comment]
fuck

_Sent from my Galaxy J7 Prime using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Lireoy** [comment]
I guess this is related
![image](https://user-images.githubusercontent.com/34489456/52906457-93cb7a80-324c-11e9-8771-5485266a8b14.png)

**Comment by Doges** [comment]
> I guess this is related
> ![image](https://user-images.githubusercontent.com/34489456/52906457-93cb7a80-324c-11e9-8771-5485266a8b14.png)

it is but u did something wrong
