### ISSUE TITLE
Make triggered command apply the effect on the uploaded image

### ISSUE THREAD

**Issue by zerinho6** [SwitchbladeBot/switchblade#709]
**Is your feature request related to a problem? Please describe.**
Yes and No, right now if you use the command triggered i'll apply the effect to your avatar, it doesn't even check if you've sent a image with the command.

**Describe the solution you'd like**
Case a image as sent with the command it should apply the effect to the image and not the user avatar.

**Additional context**
It would be nice to it also detect links like NotSoBot.

**Comment by metehus** [comment]
To be done after #710
