### ISSUE TITLE
Smart image parameter

### ISSUE THREAD

**Issue by metehus** [SwitchbladeBot/switchblade#710]
A paramter that returns an url that can be an attachment, link, avatar from a mention or if theres no argument it searches for the last messages for an attachment/link or gets from the author profile

**Comment by pedrofracassi** [comment]
![image](https://user-images.githubusercontent.com/25179120/52975807-b1602780-33a5-11e9-9712-87d482a20af2.png)

I WAS WRITING THAT ISSUE!!11!

**Comment by pedrofracassi** [comment]
There should be some kind of priority about where we look for the image.

**Comment by pedrofracassi** [comment]
We should have some kind of priority when looking for the image. Here's what I think would work:
1. Link 
2. Attachment
4. Mention (gets the mentioned user's avatar)
3. Last image from channel
5. User's own avatar

**Comment by Lireoy** [comment]
if else if else if else 💯

**Comment by pedrofracassi** [comment]
exactly.

**Comment by metehus** [comment]
@pedrofracassi i think attachment comes first

**Comment by pedrofracassi** [comment]
1. Attachment
2. Link 
4. Mention (gets the mentioned user's avatar)
3. Last image from channel
5. User's own avatar
