### ISSUE TITLE
Twitter relay

### ISSUE THREAD

**Issue by orisica** [SwitchbladeBot/switchblade#711]
Hello,
I would like to propose a feature that follows specified twitter users or even better, specified twitter lists and relays their tweets to a specified discord channel. So basically a twitter feed on discord. Also please make the refresh rate quick, instant would be best if possible.
Thanks

**Comment by metehus** [comment]
Can be possible the use of lists and it would be almost instant

**Comment by pedrofracassi** [comment]
We could use webhooks or ubsubhubbub

**Comment by dpaiv0** [comment]
WebSub (abv. for PubSubHubbub) isn't that great for dev instances. Webhooks should be better, imo.

**Comment by pedrofracassi** [comment]
Why wouldn't it? WebSub seems like the way we should do it

**Comment by dpaiv0** [comment]
Twitter doesn't support WebSub protocol natively.

**Comment by dpaiv0** [comment]
Believe me, I've tried it already

**Comment by pedrofracassi** [comment]
What can we use for that then?

**Comment by dpaiv0** [comment]
#87

**Comment by pedrofracassi** [comment]
Dupe of #87
