### ISSUE TITLE
Pirate Speak Translation Command

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#714]
`s!piratespeak <text>` - Translates english text to pirate speak

**Useful packages**
https://www.npmjs.com/package/pirate-speak
https://www.npmjs.com/package/talk-like-a-pirate

**Comment by dpaiv0** [comment]
This could help with en-PT, haven't you thought of that?

**Comment by pedrofracassi** [comment]
Yes!

**Comment by dpaiv0** [comment]
will do tomorrow. assigning
