### ISSUE TITLE
Play command adds the wrong song to the queue

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#715]
![image](https://user-images.githubusercontent.com/25179120/53050850-0a4cc000-3479-11e9-9c5d-96a3afd7eed9.png)

## Links known to cause the issue
- https://www.youtube.com/watch?v=P4kE3Ap80Ls

**Comment by Doges** [comment]
that's due region, durr, we can't actually fix that

**Comment by pedrofracassi** [comment]
But it's a direct link, why wouldn't that work? Also the voice region that server is in is Brazil

**Comment by davipatury** [comment]
I'm going to investigate it.

**Comment by pedrofracassi** [comment]
Cool. Thanks.

**Comment by pedrofracassi** [comment]
Now that was fast as fuck
