### ISSUE TITLE
Objects and arrays can't be stored on the database

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#718]

**Comment by dpaiv0** [comment]
See if [this](https://stackoverflow.com/questions/19695058/how-to-define-object-in-array-in-mongoose-schema-correctly-with-2d-geo-index) helps

**Comment by Doges** [comment]
remove parse????????????????????????????????????????????????

**Comment by pedrofracassi** [comment]
Will it break anything?

**Comment by Doges** [comment]
no
