### ISSUE TITLE
Flags parse error

### ISSUE THREAD

**Issue by metehus** [SwitchbladeBot/switchblade#733]
![image](https://user-images.githubusercontent.com/22124518/53288692-42e6e500-376a-11e9-9734-2090da2ffdeb.png)
 problem on the new structure

**Comment by davipatury** [comment]
![corno](https://cdn.discordapp.com/attachments/514534829744848906/549025570034417664/unknown.png)

**Comment by davipatury** [comment]
Fixed by 0c545d6d6c32837af6f244606f7b10914c3fcaf6
