### ISSUE TITLE
Cowsay Bug

### ISSUE THREAD

**Issue by JackCrispy** [SwitchbladeBot/switchblade#744]
**Bug description**
it say undefined when you do s!cowsay

**How to reproduce**
Steps to reproduce the unusual behavior:
1. Run s!cowsay

**Expected behavior**
-For it to not say undefined, and say something like insert text here kid

**Screenshots**
nah to lazy

**Additional context**
nope kthx.

**Comment by perronosaurio** [comment]
please, add more context

**Comment by Doges** [comment]
missing commandusage

**Comment by metehus** [comment]
i saw this on morning and i thought i was alucinating dont ask me

_Sent from Android Bus Device using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by perronosaurio** [comment]
oooo

**Comment by Doges** [comment]
fixed at 25a45d0
