### ISSUE TITLE
Command permissions

### ISSUE THREAD

**Issue by metehus** [SwitchbladeBot/switchblade#745]
Create a command and a page on the dashboard to configure permissions for the commands in channels and roles.
Each channel will have their own configuration on each role for what command will be enabled/disabled

For example, we have the channel `#chat` and the channel `#bots` and i want to enable the use of commands on `#chat` only for `@staff` and disable the `s!cowsay` for every role in every channel.

For that example we gonna use
- `s!config command * #chat * false` to disable `*` (all) commands on `#chat` for `*`(all roles)
- `s!config cmd * #chat @staff on` to enable `*` commands on `#chat` for `@staff`
- `s!config cmd cowsay * * off` to disable `s!cowsay` on `*` for `*`

## ADDITIONAL

- Creating a CommandParameter
- Maybe using `**` to select all commands, even the ones not released yet
- Saving on the database only disabled commands to save space (don't know how this would work with the special character `**` above)
- NSFW tagged commands can only be enabled/disabled on nsfw tagged channels    
- Using `c:music` to select a entire category

**Comment by perronosaurio** [comment]
all instead of *, its more intuitive

**Comment by metehus** [comment]
@perronosaurio what about a s!all or whatever

**Comment by perronosaurio** [comment]
s!config command all #chat all disable idk

**Comment by perronosaurio** [comment]
s!config command cowsay #chat --disable --roles @everyone

**Comment by pedrofracassi** [comment]
I'd say we should keep that kind of thing dashboard-only. It gets too complicated for a command

**Comment by metehus** [comment]
i was thinking about `s!config command disable cowsay #chat @everyone` but i think it would be more pattern if we usse the booleanparameter

**Comment by metehus** [comment]
ok so we doing only on dashboard like @perronosaurio and @pedrofracassi said

**Comment by metehus** [comment]
ok but, we are gonna make a inherit system like discord?
like:
```
@everyone: {
  s!play: disabled,
  s!help: enabled
}
@DJ: {
  s!play: enabled,
  s!cowsay: disabled,
  s!hpelp: inherit
}
```
this will make the s!help on the @DJ command be enabled too, or we use booleans? and the permissio is set by the highest role, which can be hard for configure all roles for admins, but this will take a bunch of space on database  as i see this can be stored like this:
```
guild.channels: [
  {
    id: '29000472890753',
    roles: [
      {
        id: '3026482916025', // dj
        disabledCommands: [ 'cowsay' ],
        inheritCommsnds: [ 'help' ]
      }
    ]
  }
]
```
