### ISSUE TITLE
chorus: Null download links are not handled

### ISSUE THREAD

**Issue by Paturages** [SwitchbladeBot/switchblade#752]
**Bug description**

Some of the songs on chorus are part of packs (e.g. monthly packs...) or setlists (e.g. Anti Hero, Djent Hero, Circuit Breaker...). It is almost systematic that single song downloads are hidden for recent setlists or packs, resulting in a `null` download link. This is intended behavior from chorus.

The bug is that Switchblade still displays a `Download **<charter>**'s chart` line without a link.

**How to reproduce**

```
c!chorus name="synchronal"
# Choose 1st and only result
1
```

However, since the March monthly pack is out and I have to get it on chorus today, the February pack will no longer have `null` links. In which case, replace the query by `name="soranone"`.

**Expected behavior**

The embed should still credit the charter (e.g. `Chart by <charter>`), but the download link that's promoted should be the setlist/pack link.

**Screenshots**

![image](https://user-images.githubusercontent.com/9801350/53734480-6b669180-3e84-11e9-9a90-37ea0073b47c.png)

**Comment by pedrofracassi** [comment]
![image](https://user-images.githubusercontent.com/25179120/67637919-17e6ff00-f8be-11e9-96e1-6ddbb3742bc9.png)

**Comment by pedrofracassi** [comment]
Marking it as canary as the command doesn't even work in production (a fix was pushed to canary, but this issue remains)

**Comment by Doges** [comment]
> 
> 
> Marking it as canary as the command doesn't even work in production (a fix was pushed to canary, but this issue remains)

i think that worked ~2 years later, closing the issue
![DiscordCanary_527sd7RzLm](https://user-images.githubusercontent.com/31023616/109441531-3c07a280-7a14-11eb-8ab8-c3ad43383a85.png)
