### ISSUE TITLE
Update command Help

### ISSUE THREAD

**Issue by ArthurProgrammer** [SwitchbladeBot/switchblade#758]
You'd can update this command putting reaction sistem.

**Comment by pedrofracassi** [comment]
Please clarify? I don't get what you mean.

**Comment by ArthurProgrammer** [comment]
For example: http://prntscr.com/mv3tb8, that sistem

**Comment by pedrofracassi** [comment]
Closing this as a commands page is already planned on our website. Soon enough, `s!help` will only link to that page.
