### ISSUE TITLE
Default icon on serverinfo

### ISSUE THREAD

**Issue by metehus** [SwitchbladeBot/switchblade#759]
On the serverinfo command, use the nirewen api for default images, like this:
`https://guild-default-icon.herokuapp.com/SB` for the Switchblade Community
![SB](https://guild-default-icon.herokuapp.com/SB)

**Comment by pedrofracassi** [comment]
Either that or find out how these are generated and make them bot-side instead of calling an API

**Comment by davipatury** [comment]
Canvas + `Guild.nameAcronym`
