### ISSUE TITLE
Paged embed system

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#76]

**Comment by bolsomito** [comment]
To which commands, for example?

**Comment by bolsomito** [comment]
@pedrofracassi

**Comment by pedrofracassi** [comment]
Help, if the text starts getting too big, for example.

**Comment by bolsomito** [comment]
for #79 for example?

**Comment by pedrofracassi** [comment]
Yes, if it starts getting too big

**Comment by dpaiv0** [comment]
and this ffs

**Comment by pedrofracassi** [comment]
@dpaiv0 	how's this going?

**Comment by dpaiv0** [comment]
It's at #801, but idk what to add more
