### ISSUE TITLE
Message link preview 

### ISSUE THREAD

**Issue by zerinho6** [SwitchbladeBot/switchblade#760]
Discord added a new feature that when you right click on a message there's a option to copy the message link, It would be cool to make a command where you put the link as argument and the bot tries to find the content of the message and reply with it, or even a module that you can enable to the actual guild that when someone send a link in message link form it automatically sends a preview of the content in that message.

_Sent from my Galaxy J1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by metehus** [comment]
we could use webhook to custom profile or that would be rate limited?

**Comment by zerinho6** [comment]
The original idea would it do be rate limited, but i din't think a lot on programming side so you guys can choose that.

**Comment by zerinho6** [comment]
Here's some examples of how i've think about it/my version of it:
![image](https://user-images.githubusercontent.com/17533910/54088228-96e0f480-433a-11e9-8c98-46c02f219b35.png)
![image](https://user-images.githubusercontent.com/17533910/54088233-a2342000-433a-11e9-86d4-d3ab6715e12e.png)

**Comment by beescuit** [comment]
Whoever is going to do this, just be careful not to send things that are in NSFW channels into arbitrary ones

**Comment by pedrofracassi** [comment]
Nicely noted, @beescuit.

**Comment by metehus** [comment]
thanks biscuit very cool

**Comment by metehus** [comment]
so, are we gonna use webhook? if we use we can reproduce 100% the original message

**Comment by metehus** [comment]
not hard tho i think i can do it

**Comment by dpaiv0** [comment]
it's not complicated tho

**Comment by dpaiv0** [comment]
@metehus the webhook thing is amazing, so make the bot & the user that instantiated the command require the ``MANAGE_WEBHOOK`` permission

**Comment by dpaiv0** [comment]
i mean, the user doesn't need the MANAGE_WEBHOOK permission

**Comment by metehus** [comment]
yes
