### ISSUE TITLE
Problem with userinfo command

### ISSUE THREAD

**Issue by Flame-0** [SwitchbladeBot/switchblade#768]
Mentioning your own username with the userinfo command isn't working

![s0001](https://user-images.githubusercontent.com/40175769/54493634-31c66980-490d-11e9-9876-948e9126320a.png)

**Comment by Doges** [comment]
actually, thats not a bug but, its kinda simple to fix it then i m keeping it open

**Comment by dpaiv0** [comment]
Fixing it
