### ISSUE TITLE
Move message command

### ISSUE THREAD

**Issue by zerinho6** [SwitchbladeBot/switchblade#769]
I've made a personal command for my guild where the staff can move a message from channel to another, we use it for message that shouldn't be on *x* channel because the content of *x* message is for *y* channel.

So i think that it would ne a nice moderation command on switchblade where the user need MANAGE_MESSAGES permission to use that command and the usage would be something like: `prefix.move <messageLink> <channelID>`, 
literal: `s!move https://discordapp.com/channels/445203868624748555/514534829744848906/556942345703129109 445631443490832394`

Message Link being the same argument that i've used here https://github.com/SwitchbladeBot/switchblade/issues/760#issuecomment-471322538

and channelID could be a channel mention or the channelID, this command would have rules like: you can't move a message from another guild because that would be bs, you can't move message from members that have a role where the position is the same or higher than your highest role & guild owner and you can't move messages from a nsfw channel to a not nsfw channel. (Nicely noted beescuit.)

**Comment by metehus** [comment]
good

**Comment by fernando4578** [comment]
g👀d

**Comment by moruzerinho6** [comment]
Can someone assign me on this issue? Since that account is the old one.

**Comment by pedrofracassi** [comment]
done
