### ISSUE TITLE
Advanced auto-reply

### ISSUE THREAD

**Issue by zerinho6** [SwitchbladeBot/switchblade#778]
You know those bots with auto-reply feature, where you type the expected string and a response to it, so the advanced version would be for example `s!acmd there's {{amont}} bears || I don't see {{amount}} bears`, in action:

User: there's 5 bears
Bot: I don't see 5 bears

The entire argument 2 would be considered as `amount`.

This seems pretty complex to do but who knows, you guys are crazy.

**Comment by pedrofracassi** [comment]
We're actually considering putting AI into this

**Comment by zerinho6** [comment]
![image](https://user-images.githubusercontent.com/17533910/55261519-f6e7fe00-5249-11e9-8507-fc0bf5d4a5b9.png)

**Comment by pedrofracassi** [comment]
Closing as #570 pretty much covers this one.
