### ISSUE TITLE
Role list command (with IDs)

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#79]

**Comment by dpaiv0** [comment]
will do this also

**Comment by metehus** [comment]
> will do this also
> >  on 31 Jan 2019

**Comment by jaxxibae** [comment]
sifude

A quarta, 5/08/2020, 17:14, Matheus Dias <notifications@github.com>
escreveu:

**Comment by Doges** [comment]
> 
> 
> > will do this also
> > > on 31 Jan 2019

cade

**Comment by moruzerinho6** [comment]
Will do when pagination comes to master, please mention me when it does.
