### ISSUE TITLE
JoinLock Custom Message

### ISSUE THREAD

**Issue by Lireoy** [SwitchbladeBot/switchblade#806]
**Is your feature request related to a problem? Please describe.**
yes. current joinlock doesn't specify the reason for joinlock

**Describe the solution you'd like**
be able to set a custom text mesage as why the joinlock is switched on. so users who encounter joinlock, have some clue.

**Additional context**
moptop stolen situation after-lockdown

**Comment by pedrofracassi** [comment]
This is actually already working on the bot's side, but we need to implement it on the dashboard

**Comment by Doges** [comment]
> This is actually already working on the bot's side, but we need to implement it on the dashboard

like, its not actually working, i m doing the bot side and sending it to canary

**Comment by pedrofracassi** [comment]
It's working as in joinlock already supports custom messages
