### ISSUE TITLE
"Ah shit, here we go again" generator

### ISSUE THREAD

**Issue by jaxxibae** [SwitchbladeBot/switchblade#818]
![meme template](https://i.imgur.com/yZ6dsbb.png)

**Comment by justandras** [comment]
too late

**Comment by Purhan** [comment]
May I work on this? I have been into discord bots lately. :)

**Comment by Purhan** [comment]
Hold up, is this an image-manipulation issue? If that's the case, my bad, the PR above simply just sends a GIF. Should I close it? (I'm sorry I didn't realize that sooner)

**Comment by jaxxibae** [comment]
Yep, it's an image manipulation command. If you need help, you can look at other commands for reference, like s!quieres

**Comment by pedrofracassi** [comment]
@Purhan yeah, I think I described it poorly in the issue, but the command is supposed to overlay that image on top of another given image.

**Comment by CamHardy** [comment]
Hold my beer
