### ISSUE TITLE
Mongodb set client.database as object same without database url on env.

### ISSUE THREAD

**Issue by fernando457829** [SwitchbladeBot/switchblade#840]
**Bug description**
Self explain.

**How to reproduce**
Run bot without database url connection and run any command.

**Expected behavior**
Ignore it and run bot normally.

**Screenshots**
Screenshot of client.database:
![image](https://user-images.githubusercontent.com/29582786/58297054-9f2ec480-7dac-11e9-984a-2485868748f8.png)

**Comment by pedrofracassi** [comment]
cc @davipatury

**Comment by pedrofracassi** [comment]
I love that you write "Self explanatory" on the description but I don't understand anything

Please explain what you want
