### ISSUE TITLE
Display users on the server that plays x game

### ISSUE THREAD

**Issue by LBlend** [SwitchbladeBot/switchblade#873]
**Describe the solution you'd like**
Let the user specify a game and make it return a list of users on the server that plays the specified game

**Additional context**
http://iamavirg.in/d0d98c504e8.png

**Comment by hi15** [comment]
I will work on it.

**Comment by hi15** [comment]
@LBlend the link of additional context is not working.

**Comment by LBlend** [comment]
> 
> 
> @LBlend the link of additional context is not working.
https://i.imgur.com/27WyYZo.png

**Comment by LBlend** [comment]
https://i.imgur.com/27WyYZo.png @hi15

**Comment by hi15** [comment]
Yes, thank you =)

**Comment by metehus** [comment]
good luck and good hacktober

**Comment by hi15** [comment]
Sorry I read docs and wiki, but I didn't get how could I test commands local.

**Comment by pedrofracassi** [comment]
Can you DM me on Discord so I can help you out?

**Comment by pedrofracassi** [comment]
I'm **pedrofracassi#4623**, shoot me a DM anytime :)

**Comment by Doges** [comment]
Discord won't let us do this anymore, closing this issue.
