### ISSUE TITLE
Datadog Integration

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#884]
- Add `connect-datadog` to send information about the API to DataDog
- Add `node-dogstatsd` to send information about the bot's events to DataDog

Here's a few things we can log:
- Command runs
- All events we currently listen
- Channel metadata
- others

[Dank Memer's legacy code](https://github.com/DankMemer/Dank-Memer-Legacy) is an awesome example of how to do it.

**Comment by pedrofracassi** [comment]
So it looks like you need a DogStatsD server to send the metrics to. That runs locally on the machine that runs the bot. Luckily, the Datadog Agent has a DogStatsD server that can be enabled [by followin this](https://docs.datadoghq.com/developers/dogstatsd/#agent).

`[dogstatsd-local](https://github.com/jonmorehouse/dogstatsd-local)` seems like a good option for local debugging during development. Needs to be built with GO, though.

**Comment by Doges** [comment]
yeah
