### ISSUE TITLE
Change gmaps api to HERE api

### ISSUE THREAD

**Issue by metehus** [SwitchbladeBot/switchblade#888]
do it asap and we not using fucking bing maps

**Comment by Doges** [comment]
yes, we are using bing maps now

**Comment by TheOnlyGhostwolf** [comment]
F

**Comment by pedrofracassi** [comment]
Oof

**Comment by pedrofracassi** [comment]
Is this still an issue, @metehus?

**Comment by Doges** [comment]
> Is this still an issue, @metehus?

yes

**Comment by metehus** [comment]
> Is this still an issue, @metehus?

yes, we also need to change the darkSky API later

**Comment by Doges** [comment]
the here api requires to get a new token every x seconds, what we can do about it? because i think requesting a new token in every request is not that good

**Comment by metehus** [comment]
> the here api requires to get a new token every x seconds, what we can do about it? because i think requesting a new token in every request is not that good

i mean.... most other apps do that, like spotify API. Also there's no need to regenerate every request, we can just generate at boot and save. Whent there's a request, we check if it's expired, and if it is, we generate again and save again.

**Comment by pedrofracassi** [comment]
> > the here api requires to get a new token every x seconds, what we can do about it? because i think requesting a new token in every request is not that good
> 
> i mean.... most other apps do that, like spotify API. Also there's no need to regenerate every request, we can just generate at boot and save. Whent there's a request, we check if it's expired, and if it is, we generate again and save again.

Yup, just like any oAuth-authenticated request.
