### ISSUE TITLE
Ignore commands with space after the prefix

### ISSUE THREAD

**Issue by justandras** [SwitchbladeBot/switchblade#890]
**Is your feature request related to a problem? Please describe.**
On another server someone accidentally joke banned someone by doing `! ban {@username}`
Most bots ignore that

**Describe the solution you'd like**
Allow users to turn this feature on on the dashboard, and make it so that it's turned off by default so bladey ignores commands with a space by default. Make this feature bind to the user not the server.

**Describe alternatives you've considered**
none

**Additional context**
Bottom text

**Comment by pedrofracassi** [comment]
Uh that should probably be toggleable

**Comment by justandras** [comment]
> Uh that should probably be toggleable

read the full issue dumb dumb

**Comment by pedrofracassi** [comment]
oh sorry

am dumb dumb

**Comment by pedrofracassi** [comment]
I'm not sure of how I feel about it being toggleable per user and not per server. Might get confusing.

**Comment by justandras** [comment]
It would also be confusing for the user if they they can use it on one server and not the other. It's more of a personal preference, it's not important for the server, but it's important for the user.

**Comment by justandras** [comment]
+
If someone uses a command with space after this fix has been rolled out send an embed saying:

From now on you have to allow bladey to listen to your commands when a space is separating the prefix and the command on our dashboard or using the `s!profile togglespace` command.
You can read more about this in our (insert date here) Update Notes.

**Comment by justandras** [comment]
Or another idea: make it server toggleable, but make it overrideable on your profile. So your options on your profile settings should be: off / determined by your server / on.

**Comment by davipatury** [comment]
Fixed by #983 
(except the user option thing)
