### ISSUE TITLE
Some commands use "request" as the variable name for snekfetch

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#9]
And that's confusing.

https://github.com/SwitchbladeBot/switchblade/blob/ca3ab900854848ee830250d08605d17fde32cfe6/src/commands/memes/thinking.js#L2

https://github.com/SwitchbladeBot/switchblade/blob/ca3ab900854848ee830250d08605d17fde32cfe6/src/commands/memes/hmmm.js#L2

**Comment by bolsomito** [comment]
Fixed as of #10.
