### ISSUE TITLE
Music Inactivity Notification

### ISSUE THREAD

**Issue by Flame-0** [SwitchbladeBot/switchblade#909]
**Idea**
[Music System] Inactivity Notification

**Description**
Switchblade will leave the voice channel when Switchblade is alone, and even the queue is filled with songs.

**Examples**
> ![image](https://user-images.githubusercontent.com/40175769/59869212-5b3bd900-93c5-11e9-8bb7-9813af767158.png)

**Additional Context**
The queued songs will be cleared after the Inactivity.

**Comment by pedrofracassi** [comment]
That's something we really should do to save bandwidth. Maybe add a timeout (5 minutes?) so it doesn't immeadiately leave the channel
