### ISSUE TITLE
Money command shows the user's name even when they're the one running it.

### ISSUE THREAD

**Issue by pedrofracassi** [SwitchbladeBot/switchblade#96]
When you type `s!money` (without arguments), it says "User#0000 has X Switchcoins". I think it would be nicer if it said "You have X Switchcoins" instead.

**Comment by bolsomito** [comment]
why is "good first issue" a label smh

**Comment by pedrofracassi** [comment]
It's easy to do even if you're not familiar with the project.

**Comment by bolsomito** [comment]
ah ok, understandable
